"""
Generated by generator/gen_pydantic.py. DO NOT EDIT!
isort:skip_file
"""

import builtins
from typing import List, Dict, Any, Optional
from pydantic import BaseModel
from enum import Enum
from datetime import datetime


class BanUser(BaseModel):
    """"""

    uid: builtins.int
    """用户mid"""
    limit: builtins.int
    """封禁业务"""
    time: builtins.int
    """封禁时间"""
    mode: builtins.int
    """模式
    1:add 2:remove
    """


class ReqOpBlacklist(BaseModel):
    """"""

    ban_users: "List[BanUser]"
    """需要封禁/解封的用户信息"""


class RspOpBlacklist(BaseModel):
    """"""

    failed_users: List[builtins.int]
    """"""


ReqOpBlacklist.update_forward_refs()
BanUser.update_forward_refs()
RspOpBlacklist.update_forward_refs()
