"""
Generated by generator/gen_pydantic.py. DO NOT EDIT!
isort:skip_file
"""

import builtins
from typing import List, Dict, Any, Optional
from pydantic import BaseModel
from enum import Enum
from datetime import datetime


class Metadata(BaseModel):
    """请求元数据
    gRPC头部:x-bili-metadata-bin
    """

    access_key: builtins.str
    """登录Token"""
    mobi_app: builtins.str
    """包类型"""
    device: builtins.str
    """运行设备"""
    build: builtins.int
    """构建id"""
    channel: builtins.str
    """渠道"""
    buvid: builtins.str
    """设备buvid"""
    platform: builtins.str
    """平台类型"""


Metadata.update_forward_refs()
