"""
Generated by generator/gen_pydantic.py. DO NOT EDIT!
isort:skip_file
"""

import builtins
from typing import List, Dict, Any, Optional
from pydantic import BaseModel
from enum import Enum
from datetime import datetime


class Notify(BaseModel):
    msg_id: builtins.int
    """消息唯一标示"""
    msg_type: builtins.int
    """消息类型"""
    receiver_uid: builtins.int
    """接收方uid"""
    receiver_type: builtins.int
    """接收方类型"""
    story_version: builtins.int
    """故事的版本"""
    op_hash: builtins.int
    """操作结果的hash值"""
    op_sender: builtins.int
    """操作产生用户的uid"""
    op_content: builtins.str
    """patch内容"""


Notify.update_forward_refs()
