"""
Generated by generator/gen_pydantic.py. DO NOT EDIT!
isort:skip_file
"""
import builtins
from typing import List, Dict, Any, Optional
from pydantic import BaseModel
from enum import Enum
from datetime import datetime
import bilibiliq.internal.pb.bilibili.pagination.pagination_pb2_model
import bilibiliq.internal.pb.bilibili.app.archive.middleware.v1.preload_pb2_model
import bilibiliq.internal.pb.bilibili.app.archive.v1.archive_pb2_model


class BizType(str, Enum):
    """业务类型"""

    BizTypeNone = 'BizTypeNone'
    """"""
    BizTypeFollowVideo = 'BizTypeFollowVideo'
    """追番追剧"""
    BizTypeReserveActivity = 'BizTypeReserveActivity'
    """预约活动"""
    BizTypeJumpLink = 'BizTypeJumpLink'
    """跳转链接"""
    BizTypeFavSeason = 'BizTypeFavSeason'
    """收藏合集"""
    BizTypeReserveGame = 'BizTypeReserveGame'
    """预约游戏"""


class Category(str, Enum):
    """"""

    CategoryUnknown = 'CategoryUnknown'
    """"""
    CategorySeason = 'CategorySeason'
    """"""


class DescType(str, Enum):
    """枚举-文本类型"""

    DescTypeUnknown = 'DescTypeUnknown'
    """占位"""
    DescTypeText = 'DescTypeText'
    """文本"""
    DescTypeAt = 'DescTypeAt'
    """@"""


class ECode(str, Enum):
    """错误代码"""

    DEFAULT = 'DEFAULT'
    """正常"""
    CODE404 = 'CODE404'
    """稿件被UP主删除"""


class MaterialSource(str, Enum):
    """"""

    Default = 'Default'
    """"""
    BiJian = 'BiJian'
    """必剪"""


class OperationCardType(str, Enum):
    """卡片样式"""

    CardTypeNone = 'CardTypeNone'
    """"""
    CardTypeStandard = 'CardTypeStandard'
    """标准卡"""
    CardTypeSkip = 'CardTypeSkip'
    """原跳转卡"""


class PayState(str, Enum):
    """"""

    PayStateUnknown = 'PayStateUnknown'
    """"""
    PayStateActive = 'PayStateActive'
    """"""


class PlayerCardType(str, Enum):
    """卡片类型"""

    PlayerCardTypeNone_VALUE = 'PlayerCardTypeNone_VALUE'
    """"""
    PlayerCardTypeAttention_VALUE = 'PlayerCardTypeAttention_VALUE'
    """关注卡"""
    PlayerCardTypeOperation_VALUE = 'PlayerCardTypeOperation_VALUE'
    """运营卡"""
    PlayerCardTypeContract_VALUE = 'PlayerCardTypeContract_VALUE'
    """契约卡"""


class PremiereState(str, Enum):
    """"""

    premiere_none = 'premiere_none'
    """"""
    premiere_before = 'premiere_before'
    """"""
    premiere_in = 'premiere_in'
    """"""
    premiere_after = 'premiere_after'
    """"""


class SeasonType(str, Enum):
    """"""

    Unknown = 'Unknown'
    """"""
    Base = 'Base'
    """"""
    Good = 'Good'
    """"""


class TabOtype(str, Enum):
    """TAB跳转类型"""

    UnknownOtype = 'UnknownOtype'
    """未知类型"""
    URL = 'URL'
    """url链接"""
    TopicNA = 'TopicNA'
    """native话题活动"""
    CmURI = 'CmURI'
    """广告url"""


class TabStyle(str, Enum):
    """TAB样式"""

    UnknownStyle = 'UnknownStyle'
    """未知样式"""
    Text = 'Text'
    """文字样式"""
    Pic = 'Pic'
    """图片样式"""


class ActivityResource(BaseModel):
    """活动页资源包"""

    mod_pool_name: builtins.str
    """mod资源池名称"""
    mod_resource_name: builtins.str
    """mod资源名称"""
    bg_color: builtins.str
    """背景色"""
    selected_bg_color: builtins.str
    """选中背景色"""
    text_color: builtins.str
    """文字颜色"""
    light_text_color: builtins.str
    """浅字色"""
    dark_text_color: builtins.str
    """深字色"""
    divider_color: builtins.str
    """分割线色"""


class ActivitySeason(BaseModel):
    """大型活动合集"""

    arc: bilibiliq.internal.pb.bilibili.app.archive.v1.archive_pb2_model.Arc
    """稿件信息"""
    pages: "List[ViewPage]"
    """分P信息"""
    owner_ext: Optional["OnwerExt"] = None
    """("OnwerExt"为源码中拼写错误)"""
    req_user: Optional["ReqUser"] = None
    """稿件用户操作状态"""
    elec_rank: Optional["ElecRank"] = None
    """充电排行"""
    history: Optional["History"] = None
    """历史观看进度"""
    bvid: builtins.str
    """稿件bvid"""
    honor: Optional["Honor"] = None
    """获得荣誉信息"""
    staff: "List[Staff]"
    """联合投稿成员列表"""
    ugc_season: Optional["UgcSeason"] = None
    """UGC视频合集信息"""
    tab: Optional["Tab"] = None
    """播放页定制tab"""
    rank: Optional["Rank"] = None
    """排行榜"""
    order: Optional["Order"] = None
    """预约模块"""
    support_dislike: builtins.bool
    """是否支持点踩"""
    operation_relate: Optional["OperationRelate"] = None
    """相关推荐(运营配置+AI推荐)"""
    activity_resource: Optional["ActivityResource"] = None
    """活动页资源包"""
    short_link: builtins.str
    """短链接"""
    label: Optional["Label"] = None
    """标签"""
    dislike: Optional["Dislike"] = None
    """不感兴趣原因"""
    player_icon: Optional["PlayerIcon"] = None
    """播放图标动画配置档"""
    share_subtitle: builtins.str
    """分享副标题(已观看xxx次)"""
    cm_config: Optional["CMConfig"] = None
    """广告配置"""
    tf_panel_customized: Optional["TFPanelCustomized"] = None
    """免流面板定制"""
    argue_msg: builtins.str
    """争议信息"""
    ecode: ECode
    """错误码
    DEFAULT:正常 CODE404:视频被UP主删除
    """
    custom_config: Optional["CustomConfig"] = None
    """404页信息"""
    badge_url: builtins.str
    """评论样式"""
    desc_v2: "List[DescV2]"
    """稿件简介v2"""
    config: Optional["Config"] = None
    """"""
    online: Optional["Online"] = None
    """"""
    arc_extra: Optional["ArcExtra"] = None
    """"""
    reply_preface: Optional["ReplyStyle"] = None
    """"""


class AddContractReq(BaseModel):
    """点击签订契约-请求"""

    aid: builtins.int
    """稿件avid"""
    up_mid: builtins.int
    """UP主mid"""
    spmid: builtins.str
    """当前页面spm"""


class AdInfo(BaseModel):
    """"""

    creative_id: builtins.int
    """"""
    creative_type: builtins.int
    """"""
    creative_content: Optional["CreativeContent"] = None
    """"""
    ad_cb: builtins.str
    """"""
    card_type: builtins.int
    """"""
    extra: builtins.bytes
    """"""


class ArcExtra(BaseModel):
    """"""

    arc_pub_location: builtins.str
    """"""


class ArcsPlayer(BaseModel):
    """"""

    aid: builtins.int
    """"""
    player_info: Dict[builtins.int, builtins.str]
    """"""


class Asset(BaseModel):
    """"""

    paid: builtins.int
    """"""
    price: builtins.int
    """"""
    msg: Optional["AssetMsg"] = None
    """"""
    preview_msg: Optional["AssetMsg"] = None
    """"""


class AssetMsg(BaseModel):
    """"""

    desc1: builtins.str
    """"""
    desc2: builtins.str
    """"""


class Attention(BaseModel):
    """关注按钮卡片"""

    start_time: builtins.int
    """开始时间"""
    end_time: builtins.int
    """结束时间"""
    pos_x: builtins.float
    """位置x坐标"""
    pos_y: builtins.float
    """位置y坐标"""


class Audio(BaseModel):
    """音频稿件信息"""

    title: builtins.str
    """音频标题"""
    cover_url: builtins.str
    """音频封面url"""
    song_id: builtins.int
    """音频auid"""
    play_count: builtins.int
    """音频播放量"""
    reply_count: builtins.int
    """音频评论数"""
    upper_id: builtins.int
    """音频作者UID"""
    entrance: builtins.str
    """进入按钮文案"""
    song_attr: builtins.int
    """"""


class BadgeStyle(BaseModel):
    """"""

    text: builtins.str
    """"""
    text_color: builtins.str
    """"""
    text_color_night: builtins.str
    """"""
    bg_color: builtins.str
    """"""
    bg_color_night: builtins.str
    """"""
    border_color: builtins.str
    """"""
    border_color_night: builtins.str
    """"""
    bg_style: builtins.int
    """"""


class Bgm(BaseModel):
    """视频引用的bgm音频"""

    sid: builtins.int
    """音频auid"""
    mid: builtins.int
    """音频作者mid"""
    title: builtins.str
    """音频标题"""
    author: builtins.str
    """音频作者昵称"""
    jumpUrl: builtins.str
    """bgm页面url"""
    cover: builtins.str
    """音频封面url"""


class BizFavSeasonParam(BaseModel):
    """收藏合集参数"""

    season_id: builtins.int
    """合集id"""


class BizFollowVideoParam(BaseModel):
    """"""

    season_id: builtins.int
    """"""


class BizJumpLinkParam(BaseModel):
    """"""

    url: builtins.str
    """链接"""


class BizReserveActivityParam(BaseModel):
    """预约活动参数"""

    activity_id: builtins.int
    """活动id"""
    type: builtins.str
    """类型"""
    oid: builtins.int
    """资源id"""
    reserve_id: builtins.int
    """"""


class BizReserveGameParam(BaseModel):
    """"""

    game_id: builtins.int
    """游戏id"""


class Button(BaseModel):
    """"""

    title: builtins.str
    """按钮文案"""
    uri: builtins.str
    """跳转uri"""
    icon: builtins.str
    """"""


class ButtonStyle(BaseModel):
    """"""

    text: builtins.str
    """"""
    text_color: builtins.str
    """"""
    text_color_night: builtins.str
    """"""
    bg_color: builtins.str
    """"""
    bg_color_night: builtins.str
    """"""
    jump_link: builtins.str
    """"""


class BuzzwordConfig(BaseModel):
    """"""

    name: builtins.str
    """"""
    schema: builtins.str
    """"""
    source: builtins.int
    """"""
    start: builtins.int
    """"""
    end: builtins.int
    """"""
    follow_control: builtins.bool
    """"""
    id: builtins.int
    """"""
    buzzword_id: builtins.int
    """"""
    schema_type: builtins.int
    """"""
    picture: builtins.str
    """"""


class CacheViewReply(BaseModel):
    """"""

    arc: bilibiliq.internal.pb.bilibili.app.archive.v1.archive_pb2_model.Arc
    """"""
    pages: "List[ViewPage]"
    """"""
    owner_ext: Optional["OnwerExt"] = None
    """"""
    req_user: Optional["ReqUser"] = None
    """"""
    season: Optional["Season"] = None
    """"""
    elec_rank: Optional["ElecRank"] = None
    """"""
    history: Optional["History"] = None
    """"""
    dislike: Optional["Dislike"] = None
    """"""
    player_icon: Optional["PlayerIcon"] = None
    """"""
    bvid: builtins.str
    """"""
    short_link: builtins.str
    """"""
    share_subtitle: builtins.str
    """"""
    tf_panel_customized: Optional["TFPanelCustomized"] = None
    """"""
    online: Optional["Online"] = None
    """"""


class CacheViewReq(BaseModel):
    """"""

    aid: builtins.int
    """"""
    bvid: builtins.str
    """"""
    trackid: builtins.str
    """"""
    ad_extra: builtins.str
    """"""
    spmid: builtins.str
    """"""
    from_spmid: builtins.str
    """"""


class Chronos(BaseModel):
    """Chronos灰度管理"""

    md5: builtins.str
    """资源包md5"""
    file: builtins.str
    """资源包"""
    sign: builtins.str
    """"""


class ChronosPkgReq(BaseModel):
    """"""

    service_key: builtins.str
    """"""
    engine_version: builtins.str
    """"""
    message_protocol: builtins.str
    """"""


class ClickActivitySeasonReq(BaseModel):
    """点击大型活动页预约-请求"""

    order_type: BizType
    """预约类型"""
    spmid: builtins.str
    """当前页面spm"""
    reserve: Optional["BizReserveActivityParam"] = None
    """预约活动参数"""
    fav_season: Optional["BizFavSeasonParam"] = None
    """收藏合集参数"""
    action: builtins.int
    """操作
    0:操作 1:取消操作
    """


class ClickPlayerCardReply(BaseModel):
    """点击播放器卡片-响应"""

    message: builtins.str
    """"""


class ClickPlayerCardReq(BaseModel):
    """点击播放器卡片-请求"""

    id: builtins.int
    """卡片id"""
    aid: builtins.int
    """稿件avid"""
    cid: builtins.int
    """视频cid"""
    action: builtins.int
    """操作
    0:操作 1:取消操作
    """
    spmid: builtins.str
    """当前页面spm"""


class CM(BaseModel):
    """广告"""

    source_content: Any
    """广告数据(需解包)"""


class CMConfig(BaseModel):
    """广告配置"""

    ads_control: Any
    """广告配置数据(需要二次解包)"""


class CmIpad(BaseModel):
    """"""

    cm: Optional["CM"] = None
    """"""
    author: bilibiliq.internal.pb.bilibili.app.archive.v1.archive_pb2_model.Author
    """"""
    stat: bilibiliq.internal.pb.bilibili.app.archive.v1.archive_pb2_model.Stat
    """"""
    duration: builtins.int
    """"""
    aid: builtins.int
    """"""


class CoinCustom(BaseModel):
    """"""

    toast: builtins.str
    """"""


class CommandDm(BaseModel):
    """互动弹幕条目信息"""

    id: builtins.int
    """弹幕id"""
    oid: builtins.int
    """对象视频cid"""
    mid: builtins.int
    """发送者mid"""
    command: builtins.str
    """互动弹幕指令"""
    content: builtins.str
    """互动弹幕正文"""
    progress: builtins.int
    """出现时间"""
    ctime: builtins.str
    """创建时间"""
    mtime: builtins.str
    """发布时间"""
    extra: builtins.str
    """扩展json数据"""
    id_str: builtins.str
    """弹幕id str类型"""


class Config(BaseModel):
    """"""

    relates_title: builtins.str
    """下方推荐项标题"""
    relates_style: builtins.int
    """"""
    relate_gif_exp: builtins.int
    """"""
    end_page_half: builtins.int
    """"""
    end_page_full: builtins.int
    """"""
    auto_swindow: builtins.bool
    """退出是否自动小窗"""
    popup_info: builtins.bool
    """"""
    abtest_small_window: builtins.str
    """"""
    rec_three_point_style: builtins.int
    """"""
    is_absolute_time: builtins.bool
    """"""
    new_swindow: builtins.bool
    """"""
    relates_biserial: builtins.bool
    """"""
    listener_conf: "ListenerConfig"
    """"""
    relates_feed_style: builtins.str
    """"""
    relates_feed_popup: builtins.bool
    """"""
    relates_has_next: builtins.bool
    """"""
    local_play: builtins.int
    """"""
    play_story: builtins.bool
    """"""
    arc_play_story: builtins.bool
    """"""
    story_icon: builtins.str
    """"""
    landscape_story: builtins.bool
    """"""
    arc_landscape_story: builtins.bool
    """"""
    landscape_icon: builtins.str
    """"""
    show_listen_button: builtins.bool
    """"""


class ContinuousPlayReply(BaseModel):
    """"""

    relates: "List[Relate]"
    """"""


class ContinuousPlayReq(BaseModel):
    """"""

    aid: builtins.int
    """"""
    trackid: builtins.str
    """"""
    spmid: builtins.str
    """"""
    from_spmid: builtins.str
    """"""
    autoplay: builtins.int
    """"""
    player_args: bilibiliq.internal.pb.bilibili.app.archive.middleware.v1.preload_pb2_model.PlayerArgs
    """"""
    device_type: builtins.int
    """"""
    session_id: builtins.str
    """"""
    display_id: builtins.int
    """"""


class ContractCard(BaseModel):
    """契约卡"""

    display_progress: builtins.float
    """需要触发的播放进度百分比"""
    display_accuracy: builtins.int
    """触发位置的前后误差(单位ms)"""
    display_duration: builtins.int
    """展示持续时间(单位ms)"""
    show_mode: builtins.int
    """弹出模式
    0: 原有模式 1: 半屏弹出 2: 全屏、半屏均弹出
    """
    page_type: builtins.int
    """提示页面
    0: 原有页面 1: 6.23版本新页面
    """
    upper: Optional["UpperInfos"] = None
    """UP主信息"""
    is_follow_display: builtins.int
    """"""
    text: Optional["ContractText"] = None
    """"""
    follow_display_end_duration: builtins.int
    """"""
    is_play_display: builtins.int
    """"""
    is_interact_display: builtins.int
    """"""
    play_display_switch: builtins.bool
    """"""


class ContractText(BaseModel):
    """"""

    title: builtins.str
    """"""
    subtitle: builtins.str
    """"""
    inline_title: builtins.str
    """"""


class CreativeContent(BaseModel):
    """"""

    title: builtins.str
    """"""
    description: builtins.str
    """"""
    button_title: builtins.str
    """"""
    video_id: builtins.int
    """"""
    username: builtins.str
    """"""
    image_url: builtins.str
    """"""
    image_md5: builtins.str
    """"""
    log_url: builtins.str
    """"""
    log_md5: builtins.str
    """"""
    url: builtins.str
    """"""
    click_url: builtins.str
    """"""
    show_url: builtins.str
    """"""


class CustomConfig(BaseModel):
    """404页信息"""

    redirect_url: builtins.str
    """重定向页面url"""


class DescV2(BaseModel):
    """特殊稿件简介"""

    text: builtins.str
    """文本内容"""
    type: DescType
    """文本类型"""
    uri: builtins.str
    """点击跳转链接"""
    rid: builtins.int
    """资源ID"""


class Dislike(BaseModel):
    """不喜欢原因"""

    title: builtins.str
    """标题"""
    subtitle: builtins.str
    """"""
    reasons: "List[DislikeReasons]"
    """原因项列表"""


class DislikeReasons(BaseModel):
    """不喜欢原因项"""

    id: builtins.int
    """类型
    1:全部类型 3:TAG 4:UP主
    """
    mid: builtins.int
    """相关UP主mid"""
    rid: builtins.int
    """相关分区tid"""
    tag_id: builtins.int
    """相关TAG id"""
    name: builtins.str
    """相关名称"""


class DM(BaseModel):
    """分P弹幕信息"""

    closed: builtins.bool
    """分P是否关闭弹幕
    0:正常 1:关闭
    """
    real_name: builtins.bool
    """"""
    count: builtins.int
    """分P弹幕总数"""


class ElecRank(BaseModel):
    """充电排行信息"""

    list: "List[ElecRankItem]"
    """充电排行列表"""
    count: builtins.int
    """充电用户数"""
    text: builtins.str
    """"""


class ElecRankItem(BaseModel):
    """充电用户信息"""

    avatar: builtins.str
    """用户头像url"""
    nickname: builtins.str
    """用户昵称"""
    message: builtins.str
    """充电留言"""
    mid: builtins.int
    """用户mid"""


class Episode(BaseModel):
    """视频合集单话信息"""

    id: builtins.int
    """合集单话id"""
    aid: builtins.int
    """稿件avid"""
    cid: builtins.int
    """视频1P cid"""
    title: builtins.str
    """稿件标题"""
    cover: builtins.str
    """稿件封面url"""
    coverRightText: builtins.str
    """投稿时间显示文案"""
    page: bilibiliq.internal.pb.bilibili.app.archive.v1.archive_pb2_model.Page
    """视频分P信息"""
    stat: bilibiliq.internal.pb.bilibili.app.archive.v1.archive_pb2_model.Stat
    """视频状态数"""
    bvid: builtins.str
    """稿件bvid"""
    author: bilibiliq.internal.pb.bilibili.app.archive.v1.archive_pb2_model.Author
    """稿件UP主信息"""
    author_desc: builtins.str
    """"""
    badge_style: Optional["BadgeStyle"] = None
    """"""
    need_pay: builtins.bool
    """"""
    episode_pay: builtins.bool
    """"""
    free_watch: builtins.bool
    """"""
    first_frame: builtins.str
    """"""


class ExposePlayerCardReq(BaseModel):
    """播放器卡片曝光-请求"""

    card_type: PlayerCardType
    """卡片类型"""
    aid: builtins.int
    """稿件avid"""
    cid: builtins.int
    """视频cid"""
    spmid: builtins.str
    """当前页面spm"""


class FeedViewItem(BaseModel):
    """"""

    view: Optional["ViewReply"] = None
    """"""
    goto: builtins.str
    """"""
    uri: builtins.str
    """"""
    track_id: builtins.str
    """"""


class FeedViewReply(BaseModel):
    """"""

    list: "List[FeedViewItem]"
    """"""
    has_next: builtins.bool
    """"""


class FeedViewReq(BaseModel):
    """"""

    aid: builtins.int
    """"""
    bvid: builtins.str
    """"""
    spmid: builtins.str
    """"""
    from_spmid: builtins.str
    """"""
    player_args: bilibiliq.internal.pb.bilibili.app.archive.middleware.v1.preload_pb2_model.PlayerArgs
    """"""
    display_id: builtins.int
    """"""
    session_id: builtins.str
    """"""
    page_version: builtins.str
    """"""
    from_track_id: builtins.str
    """"""


class GetArcsPlayerReply(BaseModel):
    """"""

    arcs_player: "List[ArcsPlayer]"
    """"""


class GetArcsPlayerReq(BaseModel):
    """"""

    play_avs: "List[PlayAv]"
    """"""
    player_args: bilibiliq.internal.pb.bilibili.app.archive.middleware.v1.preload_pb2_model.PlayerArgs
    """"""


class GoodsInfo(BaseModel):
    """"""

    goods_id: builtins.str
    """"""
    category: builtins.int
    """"""
    goods_price: builtins.int
    """"""
    pay_state: PayState
    """"""
    goods_name: builtins.str
    """"""
    price_fmt: builtins.str
    """"""


class History(BaseModel):
    """稿件观看进度"""

    cid: builtins.int
    """播放进度分P cid"""
    progress: builtins.int
    """播放进度时间
    0:未观看 -1:已看完 正整数:播放时间进度
    """


class Honor(BaseModel):
    """稿件获得荣誉信息"""

    icon: builtins.str
    """荣誉栏图标url"""
    icon_night: builtins.str
    """荣誉栏图标url 夜间模式"""
    text: builtins.str
    """荣誉文案"""
    text_extra: builtins.str
    """荣誉副文案"""
    text_color: builtins.str
    """标题颜色"""
    text_color_night: builtins.str
    """标题颜色 夜间模式"""
    bg_color: builtins.str
    """背景颜色"""
    bg_color_night: builtins.str
    """背景颜色 夜间模式"""
    url: builtins.str
    """跳转uri"""
    url_text: builtins.str
    """跳转角标文案"""


class IconData(BaseModel):
    """"""

    meta_json: builtins.str
    """"""
    sprits_img: builtins.str
    """"""


class Interaction(BaseModel):
    """"""

    history_node: Optional["Node"] = None
    """"""
    graph_version: builtins.int
    """"""
    msg: builtins.str
    """"""
    evaluation: builtins.str
    """"""
    mark: builtins.int
    """"""


class Label(BaseModel):
    """"""

    type: builtins.int
    """"""
    uri: builtins.str
    """"""
    icon: builtins.str
    """"""
    icon_night: builtins.str
    """"""
    icon_width: builtins.int
    """"""
    icon_height: builtins.int
    """"""
    lottie: builtins.str
    """"""
    lottie_night: builtins.str
    """"""


class LikeAnimation(BaseModel):
    """"""

    like_icon: builtins.str
    """"""
    liked_icon: builtins.str
    """"""
    like_animation: builtins.str
    """"""


class LikeCustom(BaseModel):
    """"""

    like_switch: builtins.bool
    """"""
    full_to_half_progress: builtins.int
    """"""
    non_full_progress: builtins.int
    """"""
    update_count: builtins.int
    """"""


class ListenerConfig(BaseModel):
    """"""

    jump_style: builtins.int
    """"""
    guide_bar: "ListenerGuideBar"
    """"""


class ListenerGuideBar(BaseModel):
    """"""

    show_strategy: builtins.int
    """"""
    icon: builtins.str
    """"""
    text: builtins.str
    """"""
    btn_text: builtins.str
    """"""
    show_time: builtins.int
    """"""
    background_time: builtins.int
    """"""


class Live(BaseModel):
    """直播信息"""

    mid: builtins.int
    """主播UID"""
    roomid: builtins.int
    """直播间id"""
    uri: builtins.str
    """直播间url"""
    endpage_uri: builtins.str
    """"""


class LiveOrderInfo(BaseModel):
    """直播预约信息"""

    sid: builtins.int
    """预约id"""
    text: builtins.str
    """预约条文案"""
    live_plan_start_time: builtins.int
    """直播开始时间"""
    is_follow: builtins.bool
    """是否预约"""


class MaterialLeft(BaseModel):
    """"""

    icon: builtins.str
    """"""
    text: builtins.str
    """"""
    url: builtins.str
    """"""
    left_type: builtins.str
    """"""
    param: builtins.str
    """"""
    operational_type: builtins.str
    """"""
    static_icon: builtins.str
    """"""


class MaterialRes(BaseModel):
    """"""

    id: builtins.int
    """"""
    icon: builtins.str
    """"""
    url: builtins.str
    """"""
    type: MaterialSource
    """"""
    name: builtins.str
    """"""
    bg_color: builtins.str
    """"""
    bg_pic: builtins.str
    """"""
    jump_type: builtins.int
    """"""


class Node(BaseModel):
    """"""

    node_id: builtins.int
    """"""
    title: builtins.str
    """"""
    cid: builtins.int
    """"""


class NoReply(BaseModel):
    """空回复"""


class Notice(BaseModel):
    """"""

    title: builtins.str
    """"""
    desc: builtins.str
    """"""


class OfficialVerify(BaseModel):
    """认证信息"""

    type: builtins.int
    """认证类型
    0:个人认证 1:官方认证
    """
    desc: builtins.str
    """认证名称"""


class Online(BaseModel):
    """"""

    online_show: builtins.bool
    """"""
    player_online_logo: builtins.str
    """"""


class OnwerExt(BaseModel):
    """UP主扩展信息 ("OnwerExt"为源码中拼写错误)"""

    official_verify: Optional["OfficialVerify"] = None
    """认证信息"""
    live: Optional["Live"] = None
    """直播信息"""
    vip: Optional["Vip"] = None
    """会员信息"""
    assists: List[builtins.int]
    """"""
    fans: builtins.int
    """粉丝数"""
    arc_count: builtins.str
    """总投稿数"""


class OperationCard(BaseModel):
    """老运营卡片"""

    start_time: builtins.int
    """开始时间(单位为秒)"""
    end_time: builtins.int
    """结束时间(单位为秒)"""
    icon: builtins.str
    """图标"""
    title: builtins.str
    """标题"""
    button_text: builtins.str
    """按钮文案"""
    url: builtins.str
    """跳转链接"""
    content: builtins.str
    """内容描述"""


class OperationCardNew(BaseModel):
    """内嵌操作按钮卡片"""

    id: builtins.int
    """卡片id"""
    to: builtins.int
    """结束时间"""
    status: builtins.bool
    """用户操作态
    true已操作 false未操作
    """
    card_type: OperationCardType
    """卡片类型"""
    standard: Optional["StandardCard"] = None
    """标准卡"""
    skip: Optional["OperationCard"] = None
    """老运营卡片(原B剪跳转卡)"""
    biz_type: BizType
    """"""
    follow: Optional["BizFollowVideoParam"] = None
    """追番追剧参数"""
    reserve: Optional["BizReserveActivityParam"] = None
    """预约活动参数"""
    jump: Optional["BizJumpLinkParam"] = None
    """跳转参数"""
    game: Optional["BizReserveGameParam"] = None
    """预约游戏参数"""


class OperationCardV2(BaseModel):
    """"""

    id: builtins.int
    """"""
    to: builtins.int
    """"""
    status: builtins.bool
    """"""
    biz_type: builtins.int
    """"""
    content: Optional["OperationCardV2Content"] = None
    """"""
    BizFollowVideoParam: Optional["BizFollowVideoParam"] = None
    """"""
    BizReserveActivityParam: Optional["BizReserveActivityParam"] = None
    """"""
    BizJumpLinkParam: Optional["BizJumpLinkParam"] = None
    """"""
    BizReserveGameParam: Optional["BizReserveGameParam"] = None
    """"""


class OperationCardV2Content(BaseModel):
    """"""

    title: builtins.str
    """"""
    subtitle: builtins.str
    """"""
    icon: builtins.str
    """"""
    button_title: builtins.str
    """"""
    button_selected_title: builtins.str
    """"""
    show_selected: builtins.bool
    """"""


class OperationRelate(BaseModel):
    """相关推荐(运营配置+AI推荐)"""

    title: builtins.str
    """模块标题"""
    relate_item: "List[RelateItem]"
    """相关推荐模块内容"""
    ai_relate_item: "List[Relate]"
    """AI相关推荐"""


class Order(BaseModel):
    """预约模块"""

    status: builtins.bool
    """用户操作态"""
    title: builtins.str
    """模块标题"""
    button_title: builtins.str
    """按钮文字 未操作"""
    button_selected_title: builtins.str
    """按钮文字 已操作"""
    season_stat_view: builtins.int
    """合集播放数"""
    season_stat_danmaku: builtins.int
    """合集弹幕数"""
    order_type: BizType
    """预约类型(点击时透传，直播开始前预约活动，直播开始后收藏合集)"""
    reserve: Optional["BizReserveActivityParam"] = None
    """预约活动参数"""
    fav_season: Optional["BizFavSeasonParam"] = None
    """收藏合集参数"""
    intro: builtins.str
    """合集简介"""


class PackInfo(BaseModel):
    """游戏礼包信息"""

    title: builtins.str
    """礼包标题"""
    uri: builtins.str
    """礼包页uri"""


class PlayAv(BaseModel):
    """"""

    aid: builtins.int
    """"""
    cid: builtins.int
    """"""


class PlayerIcon(BaseModel):
    """进度条动画配置"""

    url1: builtins.str
    """拖动动画配置档url"""
    hash1: builtins.str
    """拖动动画配置档hash"""
    url2: builtins.str
    """松手动画配置档url"""
    hash2: builtins.str
    """松手动画配置档hash"""
    drag_left_png: builtins.str
    """"""
    middle_png: builtins.str
    """"""
    drag_right_png: builtins.str
    """"""
    drag_data: Optional["IconData"] = None
    """"""
    nodrag_data: Optional["IconData"] = None
    """"""


class PlayerRelatesReply(BaseModel):
    """"""

    list: "List[Relate]"
    """"""


class PlayerRelatesReq(BaseModel):
    """"""

    aid: builtins.int
    """"""
    bvid: builtins.str
    """"""
    spmid: builtins.str
    """"""
    from_spmid: builtins.str
    """"""
    player_args: bilibiliq.internal.pb.bilibili.app.archive.middleware.v1.preload_pb2_model.PlayerArgs
    """"""
    session_id: builtins.str
    """"""
    from_track_id: builtins.str
    """"""


class PointMaterial(BaseModel):
    """"""

    url: builtins.str
    """"""
    material_source: builtins.int
    """"""


class PowerIconStyle(BaseModel):
    """"""

    icon_url: builtins.str
    """"""
    icon_night_url: builtins.str
    """"""
    icon_width: builtins.int
    """"""
    icon_height: builtins.int
    """"""


class Premiere(BaseModel):
    """"""

    premiere_state: PremiereState
    """"""
    start_time: builtins.int
    """"""
    service_time: builtins.int
    """"""
    room_id: builtins.int
    """"""


class PremiereArchiveReply(BaseModel):
    """"""

    premiere: Optional["Premiere"] = None
    """"""
    risk_status: builtins.bool
    """"""
    risk_reason: builtins.str
    """"""


class PremiereArchiveReq(BaseModel):
    """"""

    aid: builtins.int
    """"""


class PremiereReserve(BaseModel):
    """"""

    reserve_id: builtins.int
    """"""
    count: builtins.int
    """"""
    is_follow: builtins.bool
    """"""


class PremiereResource(BaseModel):
    """"""

    premiere: Optional["Premiere"] = None
    """"""
    reserve: Optional["PremiereReserve"] = None
    """"""
    text: Optional["PremiereText"] = None
    """"""


class PremiereText(BaseModel):
    """"""

    title: builtins.str
    """"""
    subtitle: builtins.str
    """"""
    online_text: builtins.str
    """"""
    online_icon: builtins.str
    """"""
    online_icon_dark: builtins.str
    """"""
    intro_title: builtins.str
    """"""
    intro_icon: builtins.str
    """"""
    guidance_pulldown: builtins.str
    """"""
    guidance_entry: builtins.str
    """"""
    intro_icon_night: builtins.str
    """"""


class PullClientAction(BaseModel):
    """"""

    type: builtins.str
    """"""
    pull_action: builtins.bool
    """"""
    params: builtins.str
    """"""


class Rank(BaseModel):
    """排行榜"""

    icon: builtins.str
    """排行榜icon"""
    icon_night: builtins.str
    """排行榜icon 夜间模式"""
    text: builtins.str
    """排行榜文案"""


class RankInfo(BaseModel):
    """"""

    icon_url_night: builtins.str
    """"""
    icon_url_day: builtins.str
    """"""
    bkg_night_color: builtins.str
    """"""
    bkg_day_color: builtins.str
    """"""
    font_night_color: builtins.str
    """"""
    font_day_color: builtins.str
    """"""
    rank_content: builtins.str
    """"""
    rank_link: builtins.str
    """"""


class ReasonStyle(BaseModel):
    """推荐理由样式"""

    text: builtins.str
    """"""
    text_color: builtins.str
    """日间模式文字"""
    bg_color: builtins.str
    """"""
    border_color: builtins.str
    """"""
    text_color_night: builtins.str
    """夜间模式文字"""
    bg_color_night: builtins.str
    """"""
    border_color_night: builtins.str
    """"""
    bg_style: builtins.int
    """1:填充 2:描边 3:填充 + 描边 4:背景不填充 + 背景不描边"""
    selected: builtins.int
    """"""


class RecDislike(BaseModel):
    """"""

    title: builtins.str
    """"""
    sub_title: builtins.str
    """"""
    closed_sub_title: builtins.str
    """"""
    paste_text: builtins.str
    """"""
    closed_paste_text: builtins.str
    """"""
    dislike_reason: "List[DislikeReasons]"
    """"""
    toast: builtins.str
    """"""
    closed_toast: builtins.str
    """"""


class RecThreePoint(BaseModel):
    """"""

    dislike: Optional["RecDislike"] = None
    """"""
    feedback: Optional["RecDislike"] = None
    """"""
    watch_later: builtins.bool
    """"""


class RefreshPage(BaseModel):
    """"""

    refreshable: builtins.int
    """"""
    refresh_icon: builtins.int
    """"""
    refresh_text: builtins.str
    """"""
    refresh_show: builtins.float
    """"""


class Relate(BaseModel):
    """相关推荐项"""

    aid: builtins.int
    """"""
    pic: builtins.str
    """封面url"""
    title: builtins.str
    """标题"""
    author: bilibiliq.internal.pb.bilibili.app.archive.v1.archive_pb2_model.Author
    """UP主信息"""
    stat: bilibiliq.internal.pb.bilibili.app.archive.v1.archive_pb2_model.Stat
    """稿件状态数"""
    duration: builtins.int
    """时长"""
    goto: builtins.str
    """跳转类型
    special:pgc视频 av:稿件视频 cm:广告 game:游戏
    """
    param: builtins.str
    """参数（如av号等）"""
    uri: builtins.str
    """跳转uri"""
    jump_url: builtins.str
    """"""
    rating: builtins.float
    """评分"""
    reserve: builtins.str
    """"""
    desc: builtins.str
    """备注"""
    rcmd_reason: builtins.str
    """"""
    badge: builtins.str
    """标志文字"""
    cid: builtins.int
    """1P cid"""
    season_type: builtins.int
    """"""
    rating_count: builtins.int
    """"""
    tag_name: builtins.str
    """标签文案"""
    pack_info: Optional["PackInfo"] = None
    """游戏礼包信息"""
    notice: Optional["Notice"] = None
    """"""
    button: Optional["Button"] = None
    """按钮信息"""
    trackid: builtins.str
    """spm追踪id"""
    new_card: builtins.int
    """游戏卡片新样式"""
    rcmd_reason_style: Optional["ReasonStyle"] = None
    """推荐理由样式"""
    cover_gif: builtins.str
    """"""
    cm: Optional["CM"] = None
    """广告"""
    reserve_status: builtins.int
    """游戏卡字段
    0:下载 1:预约(跳过详情) 2:预约 3:测试 4:测试+预约 5:跳过详情页
    """
    rcmd_reason_extra: builtins.str
    """"""
    rec_three_point: Optional["RecThreePoint"] = None
    """"""
    unique_id: builtins.str
    """"""
    material_id: builtins.int
    """"""
    from_source_type: builtins.int
    """"""
    from_source_id: builtins.str
    """"""
    dimension: bilibiliq.internal.pb.bilibili.app.archive.v1.archive_pb2_model.Dimension
    """"""
    cover: builtins.str
    """"""
    badge_style: Optional["ReasonStyle"] = None
    """"""
    power_icon_style: Optional["PowerIconStyle"] = None
    """"""
    reserve_status_text: builtins.str
    """"""
    dislike_report_data: builtins.str
    """"""
    rank_info_game: Optional["RankInfo"] = None
    """"""
    first_frame: builtins.str
    """"""


class RelateItem(BaseModel):
    """相关推荐内容"""

    url: builtins.str
    """跳链"""
    cover: builtins.str
    """封面"""


class RelatesFeedReply(BaseModel):
    """播放页推荐IFS-响应"""

    list: "List[Relate]"
    """"""
    has_next: builtins.bool
    """"""
    pagination: bilibiliq.internal.pb.bilibili.pagination.pagination_pb2_model.PaginationReply
    """"""


class RelatesFeedReq(BaseModel):
    """播放页推荐IFS-请求"""

    aid: builtins.int
    """"""
    bvid: builtins.str
    """"""
    spmid: builtins.str
    """"""
    from_spmid: builtins.str
    """"""
    player_args: bilibiliq.internal.pb.bilibili.app.archive.middleware.v1.preload_pb2_model.PlayerArgs
    """"""
    relates_page: builtins.int
    """"""
    session_id: builtins.str
    """"""
    autoplay: builtins.int
    """"""
    from_track_id: builtins.str
    """"""
    biz_extra: builtins.str
    """"""
    device_type: builtins.int
    """"""
    ad_extra: builtins.str
    """"""
    pagination: bilibiliq.internal.pb.bilibili.pagination.pagination_pb2_model.Pagination
    """"""
    refresh_num: builtins.int
    """"""


class RelateTab(BaseModel):
    """"""

    id: builtins.str
    """"""
    title: builtins.str
    """"""


class ReplyStyle(BaseModel):
    """"""

    badge_url: builtins.str
    """"""
    badge_text: builtins.str
    """"""
    badge_type: builtins.int
    """"""


class ReqUser(BaseModel):
    """用户操作状态"""

    attention: builtins.int
    """用户是否关注UP"""
    guest_attention: builtins.int
    """UP是否关注用户"""
    favorite: builtins.int
    """是否收藏"""
    like: builtins.int
    """是否点赞"""
    dislike: builtins.int
    """是否点踩"""
    coin: builtins.int
    """是否投币"""
    attention_level: builtins.int
    """关注等级"""
    fav_season: builtins.int
    """是否收藏合集"""
    elec_plus_btn: Optional["Button"] = None
    """"""


class ReserveReply(BaseModel):
    """"""

    reserve_id: builtins.int
    """"""


class ReserveReq(BaseModel):
    """"""

    reserve_id: builtins.int
    """"""
    reserve_action: builtins.int
    """"""
    up_id: builtins.int
    """"""


class Restriction(BaseModel):
    """"""

    is_teenagers: builtins.bool
    """"""
    is_lessons: builtins.bool
    """"""
    is_review: builtins.bool
    """"""
    disable_rcmd: builtins.bool
    """"""


class Season(BaseModel):
    """剧集信息"""

    allow_download: builtins.str
    """"""
    season_id: builtins.int
    """剧集ssid"""
    is_jump: builtins.int
    """是否重定向跳转"""
    title: builtins.str
    """剧集标题"""
    cover: builtins.str
    """剧集封面url"""
    is_finish: builtins.int
    """剧集是否完结"""
    newest_ep_id: builtins.int
    """最新一话epid"""
    newest_ep_index: builtins.str
    """最新一话标题"""
    total_count: builtins.int
    """总集数"""
    weekday: builtins.int
    """更新星期日"""
    user_season: Optional["UserSeason"] = None
    """用户追番标志"""
    player: Optional["SeasonPlayer"] = None
    """"""
    ogv_playurl: builtins.str
    """单集页面url"""


class SeasonActivityRecordReply(BaseModel):
    """"""

    activity: Optional["UgcSeasonActivity"] = None
    """"""


class SeasonActivityRecordReq(BaseModel):
    """"""

    season_id: builtins.int
    """"""
    activity_id: builtins.int
    """"""
    action: builtins.int
    """"""
    aid: builtins.int
    """"""
    cid: builtins.int
    """"""
    scene: builtins.int
    """"""
    spmid: builtins.str
    """"""


class SeasonPlayer(BaseModel):
    """"""

    aid: builtins.int
    """"""
    vid: builtins.str
    """"""
    cid: builtins.int
    """"""


class SeasonReply(BaseModel):
    """合集详情页-响应"""

    season: Optional["UgcSeason"] = None
    """合集信息"""


class SeasonReq(BaseModel):
    """合集详情页-请求"""

    season_id: builtins.int
    """合集id"""


class SeasonShow(BaseModel):
    """"""

    button_text: builtins.str
    """"""
    join_text: builtins.str
    """"""
    rule_text: builtins.str
    """"""
    checkin_text: builtins.str
    """"""
    checkin_prompt: builtins.str
    """"""


class SeasonWidgetExposeReply(BaseModel):
    """"""

    season_id: builtins.int
    """"""
    activity_id: builtins.int
    """"""


class SeasonWidgetExposeReq(BaseModel):
    """"""

    mid: builtins.int
    """"""
    type: builtins.int
    """"""
    season_id: builtins.int
    """"""
    activity_id: builtins.int
    """"""
    aid: builtins.int
    """"""
    cid: builtins.int
    """"""
    scene: builtins.int
    """"""


class Section(BaseModel):
    """视频合集小节信息"""

    id: builtins.int
    """小节id"""
    title: builtins.str
    """小节标题"""
    type: builtins.int
    """小节类型
    0:其他 1:正片
    """
    episodes: "List[Episode]"
    """单话列表"""


class ShortFormVideoDownloadReply(BaseModel):
    """短视频下载-响应"""

    has_download_url: builtins.bool
    """是否有下载分享按钮"""
    download_url: builtins.str
    """下载url"""
    md5: builtins.str
    """文件md5"""
    size: builtins.int
    """文件大小(单位为Byte)"""
    backup_download_url: builtins.str
    """"""


class ShortFormVideoDownloadReq(BaseModel):
    """短视频下载-请求"""

    aid: builtins.int
    """稿件avid"""
    cid: builtins.int
    """视频cid"""
    mid: builtins.int
    """用户mid"""
    buvid: builtins.str
    """设备buvid"""
    mobi_app: builtins.str
    """移动端包类型"""
    build: builtins.int
    """移动端版本号"""
    device: builtins.str
    """运行设备"""
    platform: builtins.str
    """平台"""
    spmid: builtins.str
    """当前页面spm"""
    restriction: Optional["Restriction"] = None
    """"""
    tf_isp: builtins.str
    """"""


class SpecialCell(BaseModel):
    """"""

    icon: builtins.str
    """"""
    icon_night: builtins.str
    """"""
    text: builtins.str
    """"""
    text_color: builtins.str
    """"""
    text_color_night: builtins.str
    """"""
    jump_url: builtins.str
    """"""
    cell_type: builtins.str
    """"""
    cell_bgcolor: builtins.str
    """"""
    cell_bgcolor_night: builtins.str
    """"""
    param: builtins.str
    """"""
    page_title: builtins.str
    """"""
    jump_type: builtins.str
    """"""
    end_icon: builtins.str
    """"""
    end_icon_night: builtins.str
    """"""
    notes_count: builtins.int
    """"""


class Staff(BaseModel):
    """合作成员信息"""

    mid: builtins.int
    """成员mid"""
    title: builtins.str
    """成员角色"""
    face: builtins.str
    """成员头像url"""
    name: builtins.str
    """成员昵称"""
    official_verify: Optional["OfficialVerify"] = None
    """成员官方信息"""
    vip: Optional["Vip"] = None
    """成员会员信息"""
    attention: builtins.int
    """是否关注该成员"""
    label_style: builtins.int
    """"""


class StandardCard(BaseModel):
    """标准卡"""

    title: builtins.str
    """卡片文案"""
    button_title: builtins.str
    """按钮文字 未操作"""
    button_selected_title: builtins.str
    """按钮文字 已操作"""
    show_selected: builtins.bool
    """已操作态是否显示"""


class subTFPanel(BaseModel):
    """免流子面板定制化配置"""

    right_btn_img: builtins.str
    """右侧按钮素材"""
    right_btn_text: builtins.str
    """右侧按钮文案"""
    right_btn_text_color: builtins.str
    """右侧按钮字体颜色"""
    right_btn_link: builtins.str
    """右侧按钮跳转链接"""
    main_label: builtins.str
    """中心主文案内容"""
    operator: builtins.str
    """运营商"""


class Tab(BaseModel):
    """TAB"""

    background: builtins.str
    """背景图片"""
    otype: TabOtype
    """跳转类型"""
    oid: builtins.int
    """类型id"""
    uri: builtins.str
    """跳转url"""
    style: TabStyle
    """样式"""
    text: builtins.str
    """文字"""
    text_color: builtins.str
    """未选中态字色"""
    text_color_selected: builtins.str
    """选中态字色"""
    pic: builtins.str
    """图片"""
    id: builtins.int
    """后台配置自增"""
    ad_tab_info: Any
    """"""


class Tag(BaseModel):
    """TAG信息"""

    id: builtins.int
    """TAD id"""
    name: builtins.str
    """TAG名"""
    likes: builtins.int
    """"""
    hates: builtins.int
    """"""
    liked: builtins.int
    """"""
    hated: builtins.int
    """"""
    uri: builtins.str
    """TAG页面uri"""
    tag_type: builtins.str
    """TAG类型
    common:普通 new:话题 act:活动
    """


class TFPanelCustomized(BaseModel):
    """免流面板定制"""

    right_btn_img: builtins.str
    """右侧按钮素材"""
    right_btn_text: builtins.str
    """右侧按钮文案"""
    right_btn_text_color: builtins.str
    """右侧按钮字体颜色"""
    right_btn_link: builtins.str
    """右侧按钮跳转链接"""
    main_label: builtins.str
    """中心主文案内容"""
    operator: builtins.str
    """运营商(cm ct cu)"""
    sub_panel: Dict[builtins.str, Optional["subTFPanel"]]
    """子面板定制化配置"""


class TIcon(BaseModel):
    """TAG图标信息"""

    icon: builtins.str
    """TAG图标url"""


class UgcSeason(BaseModel):
    """UGC视频合集信息"""

    id: builtins.int
    """合集id"""
    title: builtins.str
    """合集标题"""
    cover: builtins.str
    """合集封面url"""
    intro: builtins.str
    """合集简介"""
    sections: "List[Section]"
    """小节列表"""
    stat: Optional["UgcSeasonStat"] = None
    """合集状态数"""
    label_text: builtins.str
    """标签字色"""
    label_text_color: builtins.str
    """标签背景色"""
    label_bg_color: builtins.str
    """标签夜间字色"""
    label_text_night_color: builtins.str
    """标签夜间背景色"""
    label_bg_night_color: builtins.str
    """右侧描述文案"""
    descRight: builtins.str
    """按钮文案"""
    ep_count: builtins.int
    """分集总数"""
    season_type: SeasonType
    """合集类型"""
    show_continual_button: builtins.bool
    """"""
    ep_num: builtins.int
    """"""
    season_pay: builtins.bool
    """"""
    goods_info: Optional["GoodsInfo"] = None
    """"""
    pay_button: Optional["ButtonStyle"] = None
    """"""
    label_text_new: builtins.str
    """"""
    activity: Optional["UgcSeasonActivity"] = None
    """"""
    season_ability: List[builtins.str]
    """"""


class UgcSeasonActivity(BaseModel):
    """"""

    type: builtins.int
    """"""
    oid: builtins.int
    """"""
    activity_id: builtins.int
    """"""
    title: builtins.str
    """"""
    intro: builtins.str
    """"""
    day_count: builtins.int
    """"""
    user_count: builtins.int
    """"""
    join_deadline: builtins.int
    """"""
    activity_deadline: builtins.int
    """"""
    checkin_view_time: builtins.int
    """"""
    new_activity: builtins.bool
    """"""
    user_activity: Optional["UserActivity"] = None
    """"""
    season_show: Optional["SeasonShow"] = None
    """"""


class UgcSeasonStat(BaseModel):
    """ugc视频合集状态数"""

    season_id: builtins.int
    """合集id"""
    view: builtins.int
    """观看数"""
    danmaku: builtins.int
    """弹幕数"""
    reply: builtins.int
    """评论数"""
    fav: builtins.int
    """收藏数"""
    coin: builtins.int
    """投币数"""
    share: builtins.int
    """分享数"""
    now_rank: builtins.int
    """当前排名"""
    his_rank: builtins.int
    """历史最高排名"""
    like: builtins.int
    """总计点赞"""


class UpAct(BaseModel):
    """"""

    sid: builtins.int
    """"""
    mid: builtins.int
    """"""
    title: builtins.str
    """"""
    statement: builtins.str
    """"""
    image: builtins.str
    """"""
    url: builtins.str
    """"""
    button: builtins.str
    """"""


class UpLikeImg(BaseModel):
    """"""

    pre_img: builtins.str
    """"""
    suc_img: builtins.str
    """"""
    content: builtins.str
    """"""
    type: builtins.int
    """"""


class UpperInfos(BaseModel):
    """UP主信息"""

    fans_count: builtins.int
    """粉丝数"""
    arc_count_last_half_year: builtins.int
    """近半年投稿数"""
    first_up_dates: builtins.int
    """成为UP主时间"""
    total_play_count: builtins.int
    """总播放量"""


class UserActivity(BaseModel):
    """"""

    user_state: builtins.int
    """"""
    last_checkin_date: builtins.int
    """"""
    checkin_today: builtins.int
    """"""
    user_day_count: builtins.int
    """"""
    user_view_time: builtins.int
    """"""
    portrait: builtins.str
    """"""


class UserGarb(BaseModel):
    """用户装扮信息"""

    url_image_ani_cut: builtins.str
    """点赞动画url"""
    like_toast: builtins.str
    """"""


class UserSeason(BaseModel):
    """用户追番标志"""

    attention: builtins.str
    """关注状态
    0:未关注 1:已关注
    """


class VideoGuide(BaseModel):
    """视频引导信息"""

    attention: "List[Attention]"
    """关注按钮卡片"""
    commandDms: "List[CommandDm]"
    """互动弹幕"""
    operation_card: "List[OperationCard]"
    """运营卡片"""
    operation_card_new: "List[OperationCardNew]"
    """运营卡片新版"""
    contract_card: Optional["ContractCard"] = None
    """契约卡"""
    cards_second: "List[OperationCardV2]"
    """"""


class VideoPoint(BaseModel):
    """"""

    type: builtins.int
    """"""
    to: builtins.int
    """"""
    content: builtins.str
    """"""
    cover: builtins.str
    """"""
    logo_url: builtins.str
    """"""


class VideoShot(BaseModel):
    """"""

    pv_data: builtins.str
    """"""
    img_x_len: builtins.int
    """"""
    img_y_len: builtins.int
    """"""
    img_x_size: builtins.int
    """"""
    img_y_size: builtins.int
    """"""
    image: List[builtins.str]
    """"""


class ViewMaterial(BaseModel):
    """"""

    oid: builtins.int
    """"""
    mid: builtins.int
    """"""
    title: builtins.str
    """"""
    author: builtins.str
    """"""
    jump_url: builtins.str
    """"""


class ViewMaterialReply(BaseModel):
    """"""

    material_res: "List[MaterialRes]"
    """"""
    material_left: Optional["MaterialLeft"] = None
    """"""


class ViewMaterialReq(BaseModel):
    """"""

    aid: builtins.int
    """"""
    bvid: builtins.str
    """"""
    cid: builtins.int
    """"""


class ViewPage(BaseModel):
    """分P信息"""

    page: bilibiliq.internal.pb.bilibili.app.archive.v1.archive_pb2_model.Page
    """分P基本信息"""
    audio: Optional["Audio"] = None
    """分P对应的音频稿件"""
    dm: Optional["DM"] = None
    """分P弹幕信息"""
    download_title: builtins.str
    """下载文案"""
    download_subtitle: builtins.str
    """分P完整标题(视频标题+分P标题)"""


class ViewProgressReply(BaseModel):
    """稿件播放中数据-回复"""

    video_guide: Optional["VideoGuide"] = None
    """视频引导信息"""
    chronos: Optional["Chronos"] = None
    """Chronos灰度管理"""
    arc_shot: Optional["VideoShot"] = None
    """视频快照"""
    points: "List[VideoPoint]"
    """"""
    point_material: Optional["PointMaterial"] = None
    """"""
    point_permanent: builtins.bool
    """"""
    buzzword_periods: "List[BuzzwordConfig]"
    """名词解释列表"""


class ViewProgressReq(BaseModel):
    """稿件播放中数据-请求"""

    aid: builtins.int
    """稿件avid"""
    cid: builtins.int
    """视频cid"""
    up_mid: builtins.int
    """UP主mid"""
    engine_version: builtins.str
    """"""
    message_protocol: builtins.str
    """"""
    service_key: builtins.str
    """"""


class ViewReply(BaseModel):
    """视频页信息-响应"""

    arc: bilibiliq.internal.pb.bilibili.app.archive.v1.archive_pb2_model.Arc
    """稿件信息"""
    pages: "List[ViewPage]"
    """分P信息"""
    owner_ext: Optional["OnwerExt"] = None
    """UP主扩展信息 ("OnwerExt"为源码中拼写错误)"""
    req_user: Optional["ReqUser"] = None
    """稿件用户操作状态"""
    tag: "List[Tag]"
    """稿件TAG"""
    t_icon: Dict[builtins.str, Optional["TIcon"]]
    """TAG对应的图标"""
    season: Optional["Season"] = None
    """稿件映射的PGC剧集信息"""
    elec_rank: Optional["ElecRank"] = None
    """充电排行"""
    history: Optional["History"] = None
    """历史观看进度"""
    relates: "List[Relate]"
    """视频相关推荐列表"""
    dislike: Optional["Dislike"] = None
    """不感兴趣原因"""
    player_icon: Optional["PlayerIcon"] = None
    """播放图标动画配置档"""
    vip_active: builtins.str
    """"""
    bvid: builtins.str
    """稿件bvid"""
    honor: Optional["Honor"] = None
    """获得荣誉信息"""
    relate_tab: "List[RelateTab]"
    """相关推荐顶部tab"""
    activity_url: builtins.str
    """参与的活动页面url"""
    bgm: "List[Bgm]"
    """稿件引用bgm列表"""
    staff: "List[Staff]"
    """联合投稿成员列表"""
    argue_msg: builtins.str
    """争议信息"""
    short_link: builtins.str
    """短链接"""
    play_param: builtins.int
    """播放实验
    1:相关推荐自动播放
    """
    label: Optional["Label"] = None
    """标签"""
    ugc_season: Optional["UgcSeason"] = None
    """UGC视频合集信息"""
    config: Optional["Config"] = None
    """配置信息"""
    share_subtitle: builtins.str
    """分享副标题(已观看xxx次)"""
    interaction: Optional["Interaction"] = None
    """互动视频信息"""
    ecode: ECode
    """错误码
    DEFAULT:正常 CODE404:视频被UP主删除
    """
    custom_config: Optional["CustomConfig"] = None
    """404页信息"""
    cms: "List[CM]"
    """广告"""
    cm_config: Optional["CMConfig"] = None
    """广告配置"""
    tab: Optional["Tab"] = None
    """播放页定制tab"""
    rank: Optional["Rank"] = None
    """排行榜"""
    tf_panel_customized: Optional["TFPanelCustomized"] = None
    """免流面板定制"""
    up_act: Optional["UpAct"] = None
    """UP主发起活动"""
    user_garb: Optional["UserGarb"] = None
    """用户装扮"""
    activity_season: Optional["ActivitySeason"] = None
    """大型活动合集"""
    badge_url: builtins.str
    """评论样式"""
    live_order_info: Optional["LiveOrderInfo"] = None
    """直播预约信息"""
    desc_v2: "List[DescV2]"
    """稿件简介v2"""
    cm_ipad: Optional["CmIpad"] = None
    """"""
    sticker: "List[ViewMaterial]"
    """"""
    up_like_img: Optional["UpLikeImg"] = None
    """"""
    like_custom: Optional["LikeCustom"] = None
    """"""
    desc_tag: "List[Tag]"
    """"""
    special_cell: Optional["SpecialCell"] = None
    """"""
    online: Optional["Online"] = None
    """"""
    cm_under_player: Any
    """"""
    video_source: "List[ViewMaterial]"
    """"""
    special_cell_new: "List[SpecialCell]"
    """"""
    premiere: Optional["PremiereResource"] = None
    """"""
    refresh_special_cell: builtins.bool
    """"""
    material_left: Optional["MaterialLeft"] = None
    """"""
    notes_count: builtins.int
    """"""
    pull_action: Optional["PullClientAction"] = None
    """"""
    arc_extra: Optional["ArcExtra"] = None
    """"""
    pagination: bilibiliq.internal.pb.bilibili.pagination.pagination_pb2_model.PaginationReply
    """"""
    like_animation: Optional["LikeAnimation"] = None
    """"""
    reply_preface: Optional["ReplyStyle"] = None
    """"""
    refresh_page: Optional["RefreshPage"] = None
    """"""
    coin_custom: Optional["CoinCustom"] = None
    """"""


class ViewReq(BaseModel):
    """视频页详情页-请求"""

    aid: builtins.int
    """稿件avid(av/bv任选其一)"""
    bvid: builtins.str
    """稿件bvid(av/bv任选其一)"""
    trackid: builtins.str
    """AI trackid"""
    ad_extra: builtins.str
    """广告扩展数据"""
    qn: builtins.int
    """清晰度(旧版)"""
    fnver: builtins.int
    """流版本(旧版)"""
    fnval: builtins.int
    """流类型(旧版)"""
    force_host: builtins.int
    """是否强制使用域名(旧版)"""
    fourk: builtins.int
    """是否允许4K(旧版)"""
    spmid: builtins.str
    """当前页面spm"""
    from_spmid: builtins.str
    """上一页面spm"""
    autoplay: builtins.int
    """"""
    player_args: bilibiliq.internal.pb.bilibili.app.archive.middleware.v1.preload_pb2_model.PlayerArgs
    """视频秒开参数"""
    page_version: builtins.str
    """"""
    biz_extra: builtins.str
    """"""
    device_type: builtins.int
    """"""
    relates_page: builtins.int
    """"""
    session_id: builtins.str
    """"""
    in_feed_play: builtins.int
    """"""
    play_mode: builtins.str
    """"""
    pagination: bilibiliq.internal.pb.bilibili.pagination.pagination_pb2_model.Pagination
    """"""
    refresh: builtins.int
    """"""
    refresh_num: builtins.int
    """"""


class ViewTagReply(BaseModel):
    """"""

    special_cell_new: "List[SpecialCell]"
    """"""
    material_left: Optional["MaterialLeft"] = None
    """"""


class ViewTagReq(BaseModel):
    """"""

    aid: builtins.int
    """"""
    bvid: builtins.str
    """"""
    cid: builtins.int
    """"""
    spmid: builtins.str
    """"""


class Vip(BaseModel):
    """会员信息"""

    type: builtins.int
    """会员类型"""
    due_date: builtins.int
    """到期时间"""
    due_remark: builtins.str
    """"""
    access_status: builtins.int
    """"""
    vip_status: builtins.int
    """会员状态"""
    vip_status_warn: builtins.str
    """"""
    theme_type: builtins.int
    """"""
    label: Optional["VipLabel"] = None
    """"""


class VipLabel(BaseModel):
    """会员类型标签"""

    path: builtins.str
    """"""
    text: builtins.str
    """"""
    label_theme: builtins.str
    """"""


Live.update_forward_refs()
ReserveReply.update_forward_refs()
PremiereResource.update_forward_refs()
PointMaterial.update_forward_refs()
CommandDm.update_forward_refs()
DislikeReasons.update_forward_refs()
ContractCard.update_forward_refs()
BizReserveGameParam.update_forward_refs()
CacheViewReply.update_forward_refs()
RelatesFeedReply.update_forward_refs()
BizJumpLinkParam.update_forward_refs()
UpAct.update_forward_refs()
CMConfig.update_forward_refs()
OperationRelate.update_forward_refs()
BizReserveActivityParam.update_forward_refs()
Staff.update_forward_refs()
SeasonActivityRecordReply.update_forward_refs()
PullClientAction.update_forward_refs()
Button.update_forward_refs()
ReasonStyle.update_forward_refs()
History.update_forward_refs()
ElecRank.update_forward_refs()
PlayerIcon.update_forward_refs()
PackInfo.update_forward_refs()
CreativeContent.update_forward_refs()
Config.update_forward_refs()
BuzzwordConfig.update_forward_refs()
Bgm.update_forward_refs()
FeedViewItem.update_forward_refs()
PlayerRelatesReq.update_forward_refs()
SeasonActivityRecordReq.update_forward_refs()
Label.update_forward_refs()
AssetMsg.update_forward_refs()
ClickPlayerCardReply.update_forward_refs()
PremiereArchiveReq.update_forward_refs()
ViewPage.update_forward_refs()
CM.update_forward_refs()
StandardCard.update_forward_refs()
VideoGuide.update_forward_refs()
VipLabel.update_forward_refs()
DescV2.update_forward_refs()
ListenerGuideBar.update_forward_refs()
ChronosPkgReq.update_forward_refs()
ReplyStyle.update_forward_refs()
ClickActivitySeasonReq.update_forward_refs()
MaterialLeft.update_forward_refs()
SpecialCell.update_forward_refs()
CoinCustom.update_forward_refs()
ContractText.update_forward_refs()
BizFollowVideoParam.update_forward_refs()
PremiereReserve.update_forward_refs()
ActivitySeason.update_forward_refs()
IconData.update_forward_refs()
RecThreePoint.update_forward_refs()
CacheViewReq.update_forward_refs()
OperationCard.update_forward_refs()
PremiereText.update_forward_refs()
PlayAv.update_forward_refs()
DM.update_forward_refs()
TIcon.update_forward_refs()
Season.update_forward_refs()
ExposePlayerCardReq.update_forward_refs()
OnwerExt.update_forward_refs()
Interaction.update_forward_refs()
LikeAnimation.update_forward_refs()
SeasonWidgetExposeReq.update_forward_refs()
GetArcsPlayerReq.update_forward_refs()
UserActivity.update_forward_refs()
ArcsPlayer.update_forward_refs()
Tag.update_forward_refs()
CustomConfig.update_forward_refs()
SeasonReq.update_forward_refs()
UgcSeasonStat.update_forward_refs()
ListenerConfig.update_forward_refs()
OfficialVerify.update_forward_refs()
RefreshPage.update_forward_refs()
Attention.update_forward_refs()
ContinuousPlayReq.update_forward_refs()
Order.update_forward_refs()
Notice.update_forward_refs()
CmIpad.update_forward_refs()
OperationCardV2.update_forward_refs()
PowerIconStyle.update_forward_refs()
AddContractReq.update_forward_refs()
OperationCardNew.update_forward_refs()
VideoPoint.update_forward_refs()
Tab.update_forward_refs()
ShortFormVideoDownloadReq.update_forward_refs()
UpperInfos.update_forward_refs()
VideoShot.update_forward_refs()
ViewProgressReq.update_forward_refs()
ActivityResource.update_forward_refs()
LikeCustom.update_forward_refs()
Dislike.update_forward_refs()
RankInfo.update_forward_refs()
ReserveReq.update_forward_refs()
subTFPanel.update_forward_refs()
ViewProgressReply.update_forward_refs()
Section.update_forward_refs()
ButtonStyle.update_forward_refs()
ClickPlayerCardReq.update_forward_refs()
SeasonWidgetExposeReply.update_forward_refs()
ViewMaterial.update_forward_refs()
Honor.update_forward_refs()
ArcExtra.update_forward_refs()
Restriction.update_forward_refs()
AdInfo.update_forward_refs()
OperationCardV2Content.update_forward_refs()
Vip.update_forward_refs()
Episode.update_forward_refs()
UgcSeasonActivity.update_forward_refs()
GetArcsPlayerReply.update_forward_refs()
Premiere.update_forward_refs()
Audio.update_forward_refs()
ContinuousPlayReply.update_forward_refs()
Rank.update_forward_refs()
UserSeason.update_forward_refs()
ReqUser.update_forward_refs()
Chronos.update_forward_refs()
ViewReply.update_forward_refs()
SeasonShow.update_forward_refs()
ViewMaterialReq.update_forward_refs()
Node.update_forward_refs()
RelatesFeedReq.update_forward_refs()
Relate.update_forward_refs()
SeasonPlayer.update_forward_refs()
ViewTagReq.update_forward_refs()
BadgeStyle.update_forward_refs()
ElecRankItem.update_forward_refs()
MaterialRes.update_forward_refs()
ShortFormVideoDownloadReply.update_forward_refs()
UgcSeason.update_forward_refs()
Asset.update_forward_refs()
ViewMaterialReply.update_forward_refs()
UserGarb.update_forward_refs()
Online.update_forward_refs()
SeasonReply.update_forward_refs()
ViewTagReply.update_forward_refs()
PremiereArchiveReply.update_forward_refs()
TFPanelCustomized.update_forward_refs()
RecDislike.update_forward_refs()
RelateItem.update_forward_refs()
RelateTab.update_forward_refs()
LiveOrderInfo.update_forward_refs()
FeedViewReq.update_forward_refs()
BizFavSeasonParam.update_forward_refs()
GoodsInfo.update_forward_refs()
FeedViewReply.update_forward_refs()
ViewReq.update_forward_refs()
NoReply.update_forward_refs()
UpLikeImg.update_forward_refs()
PlayerRelatesReply.update_forward_refs()
