"""
Generated by generator/gen_pydantic.py. DO NOT EDIT!
isort:skip_file
"""

import builtins
from typing import List, Dict, Any, Optional
from pydantic import BaseModel
from enum import Enum
from datetime import datetime


class Arc(BaseModel):
    """稿件基本信息"""

    aid: builtins.int
    """稿件avid"""
    videos: builtins.int
    """稿件分P数"""
    type_id: builtins.int
    """分区id"""
    type_name: builtins.str
    """二级分区名"""
    copyright: builtins.int
    """稿件类型
    1:原创 2:转载
    """
    pic: builtins.str
    """稿件封面url"""
    title: builtins.str
    """稿件标题"""
    pubdate: builtins.int
    """稿件发布时间"""
    ctime: builtins.int
    """用户投稿时间"""
    desc: builtins.str
    """稿件简介"""
    state: builtins.int
    """稿件状态"""
    access: builtins.int
    """访问属性
    0:全部可见 10000:登录可见
    """
    attribute: builtins.int
    """属性位配置(现在无了)"""
    tag: builtins.str
    """空"""
    tags: List[builtins.str]
    """空"""
    duration: builtins.int
    """稿件总时长(单位为秒)"""
    mission_id: builtins.int
    """参与的活动id"""
    order_id: builtins.int
    """绑定的商单id"""
    redirect_url: builtins.str
    """PGC稿件强制重定向url(如番剧、影视)"""
    forward: builtins.int
    """空"""
    rights: Optional["Rights"] = None
    """控制标志"""
    author: Optional["Author"] = None
    """UP主信息"""
    stat: Optional["Stat"] = None
    """状态数"""
    report_result: builtins.str
    """空"""
    dynamic: builtins.str
    """投稿时发送的动态内容"""
    first_cid: builtins.int
    """稿件1P cid"""
    dimension: Optional["Dimension"] = None
    """稿件1P 分辨率"""
    staff_info: "List[StaffInfo]"
    """合作组成员列表"""
    season_id: builtins.int
    """UGC合集id"""
    attribute_v2: builtins.int
    """新版属性位配置(也没用)"""
    season_theme: Optional["SeasonTheme"] = None
    """"""
    short_link_v2: builtins.str
    """"""
    up_from_v2: builtins.int
    """"""
    first_frame: builtins.str
    """"""


class Author(BaseModel):
    """UP主信息"""

    mid: builtins.int
    """UP主mid"""
    name: builtins.str
    """UP主昵称"""
    face: builtins.str
    """UP主头像url"""


class Dimension(BaseModel):
    """分辨率"""

    width: builtins.int
    """宽度"""
    height: builtins.int
    """高度"""
    rotate: builtins.int
    """方向
    0:横屏 1:竖屏
    """


class Page(BaseModel):
    """分P信息"""

    cid: builtins.int
    """视频cid"""
    page: builtins.int
    """分P序号"""
    part: builtins.str
    """分P标题"""
    duration: builtins.int
    """分P时长(单位为秒)"""
    vid: builtins.str
    """外链vid"""
    desc: builtins.str
    """分P简介"""
    webLink: builtins.str
    """外链url"""
    dimension: Optional["Dimension"] = None
    """分P分辨率"""
    first_frame: builtins.str
    """"""


class Rights(BaseModel):
    """稿件控制标志"""

    bp: builtins.int
    """老版是否付费"""
    elec: builtins.int
    """允许充电"""
    download: builtins.int
    """允许下载"""
    movie: builtins.int
    """是否电影"""
    pay: builtins.int
    """PGC稿件需要付费"""
    hd5: builtins.int
    """是否高码率"""
    no_reprint: builtins.int
    """是否显示“禁止转载”标志"""
    autoplay: builtins.int
    """是否允许自动播放"""
    ugc_pay: builtins.int
    """UGC稿件需要付费(旧版)"""
    is_cooperation: builtins.int
    """是否联合投稿"""
    ugc_pay_preview: builtins.int
    """是否UGC付费预览"""
    no_background: builtins.int
    """是否禁止后台播放"""
    arc_pay: builtins.int
    """UGC稿件需要付费"""
    pay_free_watch: builtins.int
    """是否已付费可自由观看"""


class SeasonTheme(BaseModel):
    """"""

    bg_color: builtins.str
    """"""
    selected_bg_color: builtins.str
    """"""
    text_color: builtins.str
    """"""


class StaffInfo(BaseModel):
    """合作成员信息"""

    mid: builtins.int
    """成员mid"""
    title: builtins.str
    """成员角色"""
    attribute: builtins.int
    """属性位
    0:普通 1:赞助商金色标志
    """


class Stat(BaseModel):
    """状态数"""

    aid: builtins.int
    """稿件avid"""
    view: builtins.int
    """播放数(当屏蔽时为-1)"""
    danmaku: builtins.int
    """弹幕数"""
    reply: builtins.int
    """评论数"""
    fav: builtins.int
    """收藏数"""
    coin: builtins.int
    """投币数"""
    share: builtins.int
    """分享数"""
    now_rank: builtins.int
    """当前排名"""
    his_rank: builtins.int
    """历史最高排名"""
    like: builtins.int
    """点赞数"""
    dislike: builtins.int
    """点踩数(前端不可见故恒为0)"""


Dimension.update_forward_refs()
Author.update_forward_refs()
Rights.update_forward_refs()
StaffInfo.update_forward_refs()
Page.update_forward_refs()
SeasonTheme.update_forward_refs()
Arc.update_forward_refs()
Stat.update_forward_refs()
