"""
Generated by generator/gen_pydantic.py. DO NOT EDIT!
isort:skip_file
"""
import builtins
from typing import List, Dict, Any, Optional
from pydantic import BaseModel
from enum import Enum
from datetime import datetime


class FawkesReply(BaseModel):
    """"""

    config: builtins.str
    """客户端在fawkes系统中对应的已发布最新的config版本号"""
    ff: builtins.str
    """客户端在fawkes系统中对应的已发布最新的ff版本号"""


class FawkesReq(BaseModel):
    """"""

    appkey: builtins.str
    """客户端在fawkes系统的唯一名"""
    env: builtins.str
    """客户端在fawkes系统中的环境参数"""
    session_id: builtins.str
    """启动id"""


FawkesReq.update_forward_refs()
FawkesReply.update_forward_refs()
