"""
Generated by generator/gen_pydantic.py. DO NOT EDIT!
isort:skip_file
"""
import builtins
from typing import List, Dict, Any, Optional
from pydantic import BaseModel
from enum import Enum
from datetime import datetime


class FeedPagination(BaseModel):
    """"""

    page_size: builtins.int
    """"""
    offset: builtins.str
    """"""
    is_refresh: builtins.bool
    """"""


class FeedPaginationReply(BaseModel):
    """"""

    next_offset: builtins.str
    """"""
    prev_offset: builtins.str
    """"""
    last_read_offset: builtins.str
    """"""


class Pagination(BaseModel):
    """"""

    page_size: builtins.int
    """"""
    next: builtins.str
    """"""


class PaginationReply(BaseModel):
    """"""

    next: builtins.str
    """"""
    prev: builtins.str
    """"""


FeedPaginationReply.update_forward_refs()
Pagination.update_forward_refs()
FeedPagination.update_forward_refs()
PaginationReply.update_forward_refs()
