"""
Generated by generator/gen_pydantic.py. DO NOT EDIT!
isort:skip_file
"""
import builtins
from typing import List, Dict, Any, Optional
from pydantic import BaseModel
from enum import Enum
from datetime import datetime
import bilibiliq.internal.pb.bilibili.app.playurl.v1.playurl_pb2_model


class PlayViewReq(BaseModel):
    """播放页信息-请求"""

    ep_id: builtins.int
    """课程epid(与番剧不互通)"""
    cid: builtins.int
    """视频cid"""
    qn: builtins.int
    """清晰度"""
    fnver: builtins.int
    """视频流版本"""
    fnval: builtins.int
    """视频流格式"""
    download: builtins.int
    """下载模式
    0:播放 1:flv下载 2:dash下载
    """
    force_host: builtins.int
    """流url强制是用域名
    0:允许使用ip 1:使用http 2:使用https
    """
    fourk: builtins.bool
    """是否4K"""
    spmid: builtins.str
    """当前页spm"""
    from_spmid: builtins.str
    """上一页spm"""
    teenagers_mode: builtins.int
    """青少年模式"""
    prefer_codec_type: bilibiliq.internal.pb.bilibili.app.playurl.v1.playurl_pb2_model.CodeType
    """视频编码"""
    is_preview: builtins.bool
    """是否强制请求预览视频"""


class ProjectReq(BaseModel):
    """投屏地址-请求"""

    ep_id: builtins.int
    """课程epid(与番剧不互通)"""
    cid: builtins.int
    """视频cid"""
    qn: builtins.int
    """清晰度"""
    fnver: builtins.int
    """视频流版本"""
    fnval: builtins.int
    """视频流格式"""
    download: builtins.int
    """下载模式
    0:播放 1:flv下载 2:dash下载
    """
    force_host: builtins.int
    """流url强制是用域名
    0:允许使用ip 1:使用http 2:使用https
    """
    fourk: builtins.bool
    """是否4K"""
    spmid: builtins.str
    """当前页spm"""
    from_spmid: builtins.str
    """上一页spm"""
    protocol: builtins.int
    """投屏协议
    0:默认乐播 1:自建协议 2:云投屏
    """
    device_type: builtins.int
    """投屏设备
    0:默认其他 1:OTT设备
    """
    flv_proj: builtins.bool
    """是否flv格式"""


class PlayViewReply(BaseModel):
    """播放页信息-响应"""

    video_info: bilibiliq.internal.pb.bilibili.app.playurl.v1.playurl_pb2_model.VideoInfo
    """视频url信息"""
    play_conf: Optional["PlayAbilityConf"] = None
    """禁用功能配置"""


class PlayAbilityConf(BaseModel):
    """禁用功能配置"""

    background_play_disable: builtins.bool
    """后台播放"""
    flip_disable: builtins.bool
    """镜像反转"""
    cast_disable: builtins.bool
    """支持投屏"""
    feedback_disable: builtins.bool
    """反馈"""
    subtitle_disable: builtins.bool
    """字幕"""
    playback_rate_disable: builtins.bool
    """播放速度"""
    time_up_disable: builtins.bool
    """定时停止播放"""
    playback_mode_disable: builtins.bool
    """播放方式"""
    scale_mode_disable: builtins.bool
    """画面尺寸"""
    like_disable: builtins.bool
    """顶"""
    dislike_disable: builtins.bool
    """踩"""
    coin_disable: builtins.bool
    """投币"""
    elec_disable: builtins.bool
    """充电"""
    share_disable: builtins.bool
    """分享"""
    screen_shot_disable: builtins.bool
    """截图"""
    lock_screen_disable: builtins.bool
    """锁屏"""
    recommend_disable: builtins.bool
    """相关推荐"""
    playback_speed_disable: builtins.bool
    """倍速"""
    definition_disable: builtins.bool
    """清晰度"""
    selections_disable: builtins.bool
    """选集"""
    next_disable: builtins.bool
    """下一集"""
    edit_dm_disable: builtins.bool
    """编辑弹幕"""
    outer_dm_disable: builtins.bool
    """外层面板弹幕设置"""
    inner_dm_disable: builtins.bool
    """三点内弹幕设置"""
    small_window_disable: builtins.bool
    """画中画"""


class ProjectReply(BaseModel):
    """投屏地址-响应"""

    project: bilibiliq.internal.pb.bilibili.app.playurl.v1.playurl_pb2_model.PlayURLReply
    """Ellipsis"""


PlayViewReply.update_forward_refs()
PlayAbilityConf.update_forward_refs()
ProjectReply.update_forward_refs()
PlayViewReq.update_forward_refs()
ProjectReq.update_forward_refs()
