"""
Generated by generator/gen_pydantic.py. DO NOT EDIT!
isort:skip_file
"""
import builtins
from typing import List, Dict, Any, Optional
from pydantic import BaseModel
from enum import Enum
from datetime import datetime
import bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model


class DoubleCards(BaseModel):
    """"""

    small_cover_v2: Optional["SmallCoverV2"] = None
    """"""
    one_pic_v2: Optional["OnePicV2"] = None
    """"""
    three_pic_v2: Optional["ThreePicV2"] = None
    """"""


class SmallCoverV2(BaseModel):
    """"""

    base: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Base
    """"""
    cover_gif: builtins.str
    """"""
    cover_blur: builtins.int
    """"""
    cover_left_text_1: builtins.str
    """"""
    cover_left_icon_1: builtins.int
    """"""
    cover_left_text_2: builtins.str
    """"""
    cover_left_icon_2: builtins.int
    """"""
    cover_right_text: builtins.str
    """"""
    cover_right_icon: builtins.int
    """"""
    cover_right_background_color: builtins.str
    """"""
    subtitle: builtins.str
    """"""
    badge: builtins.str
    """"""
    rcmd_reason: builtins.str
    """"""
    desc: builtins.str
    """"""
    avatar: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Avatar
    """"""
    official_icon: builtins.int
    """"""
    can_play: builtins.int
    """"""
    rcmd_reason_style: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.ReasonStyle
    """"""
    rcmd_reason_style_v2: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.ReasonStyle
    """"""
    like_button: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.LikeButton
    """"""


class SmallCoverV3(BaseModel):
    """"""

    base: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Base
    """"""
    avatar: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Avatar
    """"""
    cover_left_text: builtins.str
    """"""
    cover_right_button: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Button
    """"""
    rcmd_reason: builtins.str
    """"""
    desc: builtins.str
    """"""
    official_icon: builtins.int
    """"""
    can_play: builtins.int
    """"""
    rcmd_reason_style: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.ReasonStyle
    """"""


class MiddleCoverV2(BaseModel):
    """"""

    base: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Base
    """"""
    ratio: builtins.int
    """"""
    desc: builtins.str
    """"""
    badge: builtins.str
    """"""


class LargeCoverV2(BaseModel):
    """"""

    base: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Base
    """"""
    avatar: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Avatar
    """"""
    badge: builtins.str
    """"""
    cover_right_button: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Button
    """"""
    cover_left_text_1: builtins.str
    """"""
    cover_left_icon_1: builtins.int
    """"""
    cover_left_text_2: builtins.str
    """"""
    cover_left_icon_2: builtins.int
    """"""
    rcmd_reason: builtins.str
    """"""
    official_icon: builtins.int
    """"""
    can_play: builtins.int
    """"""
    rcmd_reason_style: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.ReasonStyle
    """"""
    show_top: builtins.int
    """"""
    show_bottom: builtins.int
    """"""


class ThreeItemV2(BaseModel):
    """"""

    base: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Base
    """"""
    title_icon: builtins.int
    """"""
    more_uri: builtins.str
    """"""
    more_text: builtins.str
    """"""
    items: "List[ThreeItemV2Item]"
    """"""


class ThreeItemV2Item(BaseModel):
    """"""

    base: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Base
    """"""
    cover_left_icon: builtins.int
    """"""
    desc_text_1: builtins.str
    """"""
    desc_icon_1: builtins.int
    """"""
    desc_text_2: builtins.str
    """"""
    desc_icon_2: builtins.int
    """"""
    badge: builtins.str
    """"""


class SmallCoverV4(BaseModel):
    """"""

    base: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Base
    """"""
    cover_badge: builtins.str
    """"""
    desc: builtins.str
    """"""
    title_right_text: builtins.str
    """"""
    title_right_pic: builtins.int
    """"""


class TwoItemV2(BaseModel):
    """"""

    base: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Base
    """"""
    items: "List[TwoItemV2Item]"
    """"""


class TwoItemV2Item(BaseModel):
    base: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Base
    """"""
    badge: builtins.str
    """"""
    cover_left_text_1: builtins.str
    """"""
    cover_left_icon_1: builtins.int
    """"""


class MultiItem(BaseModel):
    """"""

    base: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Base
    """"""
    more_uri: builtins.str
    """"""
    more_text: builtins.str
    """"""
    items: "List[DoubleCards]"
    """"""


class ThreePicV2(BaseModel):
    """"""

    base: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Base
    """"""
    left_cover: builtins.str
    """"""
    right_cover_1: builtins.str
    """"""
    right_cover_2: builtins.str
    """"""
    cover_left_text_1: builtins.str
    """"""
    cover_left_icon_1: builtins.int
    """"""
    cover_left_text_2: builtins.str
    """"""
    cover_left_icon_2: builtins.int
    """"""
    cover_right_text: builtins.str
    """"""
    cover_right_icon: builtins.int
    """"""
    cover_right_background_color: builtins.str
    """"""
    badge: builtins.str
    """"""
    rcmd_reason: builtins.str
    """"""
    desc: builtins.str
    """"""
    avatar: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Avatar
    """"""
    rcmd_reason_style: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.ReasonStyle
    """"""


class OnePicV2(BaseModel):
    """"""

    base: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Base
    """"""
    cover_left_icon_1: builtins.int
    """"""
    cover_left_text_2: builtins.str
    """"""
    cover_right_text: builtins.str
    """"""
    cover_right_icon: builtins.int
    """"""
    cover_right_background_color: builtins.str
    """"""
    badge: builtins.str
    """"""
    rcmd_reason: builtins.str
    """"""
    avatar: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Avatar
    """"""
    rcmd_reason_style: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.ReasonStyle
    """"""


class LargeCoverV3(BaseModel):
    """"""

    base: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Base
    """"""
    cover_gif: builtins.str
    """"""
    avatar: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Avatar
    """"""
    top_rcmd_reason_style: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.ReasonStyle
    """"""
    bottom_rcmd_reason_style: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.ReasonStyle
    """"""
    cover_left_text_1: builtins.str
    """"""
    cover_left_icon_1: builtins.int
    """"""
    cover_left_text_2: builtins.str
    """"""
    cover_left_icon_2: builtins.int
    """"""
    cover_right_text: builtins.str
    """"""
    desc: builtins.str
    """"""
    official_icon: builtins.int
    """"""


class ThreePicV3(BaseModel):
    """"""

    base: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Base
    """"""
    left_cover: builtins.str
    """"""
    right_cover_1: builtins.str
    """"""
    right_cover_2: builtins.str
    """"""
    cover_left_text_1: builtins.str
    """"""
    cover_left_icon_1: builtins.int
    """"""
    cover_left_text_2: builtins.str
    """"""
    cover_left_icon_2: builtins.int
    """"""
    cover_right_text: builtins.str
    """"""
    cover_right_icon: builtins.int
    """"""
    cover_right_background_color: builtins.str
    """"""
    badge: builtins.str
    """"""
    rcmd_reason_style: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.ReasonStyle
    """"""


class OnePicV3(BaseModel):
    """"""

    base: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Base
    """"""
    cover_left_text_1: builtins.str
    """"""
    cover_left_icon_1: builtins.int
    """"""
    cover_right_text: builtins.str
    """"""
    cover_right_icon: builtins.int
    """"""
    cover_right_background_color: builtins.str
    """"""
    badge: builtins.str
    """"""
    rcmd_reason_style: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.ReasonStyle
    """"""


class SmallCoverV7(BaseModel):
    """"""

    base: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Base
    """"""
    desc: builtins.str
    """"""


class SmallCoverV9(BaseModel):
    """"""

    base: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Base
    """"""
    cover_left_text_1: builtins.str
    """"""
    cover_left_icon_1: builtins.int
    """"""
    cover_left_text_2: builtins.str
    """"""
    cover_left_icon_2: builtins.int
    """"""
    cover_right_text: builtins.str
    """"""
    cover_right_icon: builtins.int
    """"""
    can_play: builtins.int
    """"""
    rcmd_reason_style: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.ReasonStyle
    """"""
    up: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Up
    """"""
    left_cover_badge_style: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.ReasonStyle
    """"""
    left_bottom_rcmd_reason_style: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.ReasonStyle
    """"""


class SmallCoverConvergeV2(BaseModel):
    """"""

    base: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Base
    """"""
    cover_left_text_1: builtins.str
    """"""
    cover_left_icon_1: builtins.int
    """"""
    cover_left_text_2: builtins.str
    """"""
    cover_left_icon_2: builtins.int
    """"""
    cover_right_text: builtins.str
    """"""
    cover_right_top_text: builtins.str
    """"""
    rcmd_reason_style: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.ReasonStyle
    """"""
    rcmd_reason_style_v2: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.ReasonStyle
    """"""


class SmallChannelSpecial(BaseModel):
    """"""

    base: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Base
    """"""
    bg_cover: builtins.str
    """"""
    desc_1: builtins.str
    """"""
    desc_2: builtins.str
    """"""
    badge: builtins.str
    """"""
    rcmd_reason_style_2: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.ReasonStyle
    """"""


SmallChannelSpecial.update_forward_refs()
SmallCoverV4.update_forward_refs()
SmallCoverConvergeV2.update_forward_refs()
OnePicV3.update_forward_refs()
LargeCoverV2.update_forward_refs()
MultiItem.update_forward_refs()
LargeCoverV3.update_forward_refs()
SmallCoverV2.update_forward_refs()
DoubleCards.update_forward_refs()
SmallCoverV7.update_forward_refs()
SmallCoverV3.update_forward_refs()
ThreePicV2.update_forward_refs()
ThreeItemV2Item.update_forward_refs()
TwoItemV2Item.update_forward_refs()
ThreeItemV2.update_forward_refs()
SmallCoverV9.update_forward_refs()
TwoItemV2.update_forward_refs()
OnePicV2.update_forward_refs()
MiddleCoverV2.update_forward_refs()
ThreePicV3.update_forward_refs()
