"""
Generated by generator/gen_pydantic.py. DO NOT EDIT!
isort:skip_file
"""

import builtins
from typing import List, Dict, Any, Optional
from pydantic import BaseModel
from enum import Enum
from datetime import datetime
import bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model


class SmallCoverV5(BaseModel):
    """"""

    base: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Base
    """条目基本信息"""
    cover_gif: builtins.str
    """"""
    up: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Up
    """"""
    cover_right_text_1: builtins.str
    """封面右下角标文案"""
    right_desc_1: builtins.str
    """右侧文案1"""
    right_desc_2: builtins.str
    """右侧文案2"""
    rcmd_reason_style: (
        bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.ReasonStyle
    )
    """右侧推荐原因标签框"""
    hotword_entrance: Optional["HotwordEntrance"] = None
    """"""
    corner_mark_style: (
        bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.ReasonStyle
    )
    """直播小卡的角标"""
    right_icon_1: builtins.int
    """右侧文案1图标id"""
    right_icon_2: builtins.int
    """右侧文案2图标id"""
    left_corner_mark_style: (
        bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.ReasonStyle
    )
    """左上角角标"""
    cover_right_text_content_description: builtins.str
    """"""
    right_desc1_content_description: builtins.str
    """"""


class SmallCoverV5Ad(BaseModel):
    """"""

    base: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Base
    """"""
    cover_gif: builtins.str
    """"""
    up: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Up
    """"""
    cover_right_text1: builtins.str
    """"""
    right_desc1: builtins.str
    """"""
    right_desc2: builtins.str
    """"""
    rcmd_reason_style: (
        bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.ReasonStyle
    )
    """"""
    hotword_entrance: Optional["HotwordEntrance"] = None
    """"""
    corner_mark_style: (
        bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.ReasonStyle
    )
    """"""
    right_icon1: builtins.int
    """"""
    right_icon2: builtins.int
    """"""
    left_corner_mark_style: (
        bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.ReasonStyle
    )
    """"""
    cover_right_text_content_description: builtins.str
    """"""
    right_desc1_content_description: builtins.str
    """"""


class HotwordEntrance(BaseModel):
    """"""

    hotword_id: builtins.int
    """"""
    hot_text: builtins.str
    """"""
    h5_url: builtins.str
    """"""
    icon: builtins.str
    """"""


class LargeCoverV1(BaseModel):
    """"""

    base: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Base
    """条目基本信息"""
    cover_gif: builtins.str
    """"""
    avatar: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Avatar
    """"""
    cover_left_text_1: builtins.str
    """"""
    cover_left_text_2: builtins.str
    """"""
    cover_left_text_3: builtins.str
    """"""
    cover_badge: builtins.str
    """"""
    top_rcmd_reason: builtins.str
    """"""
    bottom_rcmd_reason: builtins.str
    """"""
    desc: builtins.str
    """"""
    official_icon: builtins.int
    """"""
    can_play: builtins.int
    """"""
    top_rcmd_reason_style: (
        bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.ReasonStyle
    )
    """"""
    bottom_rcmd_reason_style: (
        bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.ReasonStyle
    )
    """"""
    rcmd_reason_style_v2: (
        bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.ReasonStyle
    )
    """"""
    left_cover_badge_style: (
        bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.ReasonStyle
    )
    """"""
    right_cover_badge_style: (
        bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.ReasonStyle
    )
    """"""
    cover_badge_2: builtins.str
    """"""
    like_button: (
        bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.LikeButton
    )
    """"""
    title_single_line: builtins.int
    """"""
    cover_right_text: builtins.str
    """"""


class ThreeItemAllV2(BaseModel):
    """"""

    base: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Base
    """条目基本信息"""
    top_rcmd_reason_style: (
        bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.ReasonStyle
    )
    """"""
    item: "List[TwoItemHV1Item]"
    """"""


class TwoItemHV1Item(BaseModel):
    """"""

    title: builtins.str
    """"""
    cover: builtins.str
    """"""
    uri: builtins.str
    """"""
    param: builtins.str
    """"""
    args: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Args
    """"""
    goto: builtins.str
    """"""
    cover_left_text_1: builtins.str
    """"""
    cover_left_icon_1: builtins.int
    """"""
    cover_right_text: builtins.str
    """"""


class RcmdOneItem(BaseModel):
    """推荐"""

    base: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Base
    """条目基本信息"""
    topRcmdReasonStyle: (
        bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.ReasonStyle
    )
    """标签框信息"""
    item: Optional["SmallCoverRcmdItem"] = None
    """小封面推荐内容信息"""


class SmallCoverRcmdItem(BaseModel):
    """小封面推荐内容信息"""

    title: builtins.str
    """标题"""
    cover: builtins.str
    """封面url"""
    uri: builtins.str
    """跳转uri"""
    param: builtins.str
    """参数"""
    goto: builtins.str
    """跳转类型
    av:视频稿件
    """
    coverRightText1: builtins.str
    """封面右下角标文案"""
    rightDesc1: builtins.str
    """右侧文案1"""
    rightDesc2: builtins.str
    """右侧文案2"""
    coverGif: builtins.str
    """"""
    rightIcon1: builtins.int
    """右侧文案1图标id"""
    rightIcon2: builtins.int
    """右侧文案2图标id"""
    cover_right_text_content_description: builtins.str
    """"""
    right_desc1_content_description: builtins.str
    """"""


class ThreeItemV1(BaseModel):
    """"""

    base: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Base
    """条目基本信息"""
    titleIcon: builtins.int
    """"""
    moreUri: builtins.str
    """"""
    moreText: builtins.str
    """"""
    items: "List[ThreeItemV1Item]"
    """"""


class ThreeItemV1Item(BaseModel):
    """"""

    base: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Base
    """条目基本信息"""
    coverLeftText: builtins.str
    """"""
    coverLeftIcon: builtins.int
    """"""
    desc1: builtins.str
    """"""
    desc2: builtins.str
    """"""
    badge: builtins.str
    """"""


class HotTopicItem(BaseModel):
    """"""

    cover: builtins.str
    """"""
    uri: builtins.str
    """"""
    param: builtins.str
    """"""
    name: builtins.str
    """"""


class HotTopic(BaseModel):
    """"""

    base: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Base
    """条目基本信息"""
    desc: builtins.str
    """"""
    items: "List[HotTopicItem]"
    """"""


class DynamicHot(BaseModel):
    """"""

    base: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Base
    """条目基本信息"""
    top_left_title: builtins.str
    """"""
    desc1: builtins.str
    """"""
    desc2: builtins.str
    """"""
    more_uri: builtins.str
    """"""
    more_text: builtins.str
    """"""
    covers: List[builtins.str]
    """"""
    cover_right_text: builtins.str
    """"""
    top_rcmd_reason_style: (
        bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.ReasonStyle
    )
    """"""


class MiddleCoverV3(BaseModel):
    """"""

    base: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Base
    """条目基本信息"""
    desc1: builtins.str
    """"""
    desc2: builtins.str
    """"""
    cover_badge_style: (
        bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.ReasonStyle
    )
    """"""


class LargeCoverV4(BaseModel):
    """"""

    base: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Base
    """条目基本信息"""
    cover_left_text_1: builtins.str
    """"""
    cover_left_text_2: builtins.str
    """"""
    cover_left_text_3: builtins.str
    """"""
    cover_badge: builtins.str
    """"""
    can_play: builtins.int
    """"""
    up: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Up
    """"""
    short_link: builtins.str
    """"""
    share_subtitle: builtins.str
    """"""
    play_number: builtins.str
    """"""
    bvid: builtins.str
    """"""
    sub_param: builtins.str
    """"""


class PopularTopEntrance(BaseModel):
    """热门列表顶部按钮"""

    base: bilibiliq.internal.pb.bilibili.app.card.v1.common_pb2_model.Base
    """条目基本信息"""
    items: "List[EntranceItem]"
    """按钮项"""


class EntranceItem(BaseModel):
    """热门列表按钮信息"""

    goto: builtins.str
    """跳转类型"""
    icon: builtins.str
    """图标url"""
    title: builtins.str
    """标题"""
    module_id: builtins.str
    """入口模块id"""
    uri: builtins.str
    """跳转uri"""
    entrance_id: builtins.int
    """入口id"""
    bubble: Optional["Bubble"] = None
    """气泡信息"""
    entrance_type: builtins.int
    """入口类型
    1:代表分品类热门
    """


class Bubble(BaseModel):
    """气泡信息"""

    bubble_content: builtins.str
    """文案"""
    version: builtins.int
    """版本"""
    stime: builtins.int
    """起始时间"""


ThreeItemV1Item.update_forward_refs()
ThreeItemAllV2.update_forward_refs()
HotwordEntrance.update_forward_refs()
HotTopicItem.update_forward_refs()
DynamicHot.update_forward_refs()
TwoItemHV1Item.update_forward_refs()
HotTopic.update_forward_refs()
MiddleCoverV3.update_forward_refs()
PopularTopEntrance.update_forward_refs()
ThreeItemV1.update_forward_refs()
LargeCoverV4.update_forward_refs()
Bubble.update_forward_refs()
SmallCoverRcmdItem.update_forward_refs()
SmallCoverV5Ad.update_forward_refs()
EntranceItem.update_forward_refs()
SmallCoverV5.update_forward_refs()
RcmdOneItem.update_forward_refs()
LargeCoverV1.update_forward_refs()
