"""
Generated by generator/gen_pydantic.py. DO NOT EDIT!
isort:skip_file
"""
import builtins
from typing import List, Dict, Any, Optional
from pydantic import BaseModel
from enum import Enum
from datetime import datetime


class Exp(BaseModel):
    """"""

    id: builtins.int
    """"""
    bucket: builtins.int
    """"""


class Exps(BaseModel):
    """"""

    exps: "List[Exp]"
    """"""


Exp.update_forward_refs()
Exps.update_forward_refs()
