"""
Generated by generator/gen_pydantic.py. DO NOT EDIT!
isort:skip_file
"""

import builtins
from typing import List, Dict, Any, Optional
from pydantic import BaseModel
from enum import Enum
from datetime import datetime


class ErrorRequest(BaseModel):
    """"""

    error: builtins.int
    """"""
    time: builtins.int
    """"""
    delay: builtins.int
    """"""


class ErrorResponse(BaseModel):
    """"""

    host: builtins.str
    """"""
    time: builtins.int
    """"""


class PingRequest(BaseModel):
    """"""

    time: builtins.int
    """"""


class PingResponse(BaseModel):
    """"""

    host: builtins.str
    """"""
    time: builtins.int
    """"""


class SayRequest(BaseModel):
    """"""

    content: builtins.str
    """"""


class SayResponse(BaseModel):
    """"""

    host: builtins.str
    """"""
    content: builtins.str
    """"""
    time: builtins.int
    """"""


SayResponse.update_forward_refs()
ErrorRequest.update_forward_refs()
PingRequest.update_forward_refs()
ErrorResponse.update_forward_refs()
SayRequest.update_forward_refs()
PingResponse.update_forward_refs()
