"""
Generated by generator/gen_pydantic.py. DO NOT EDIT!
isort:skip_file
"""

import builtins
from typing import List, Dict, Any, Optional
from pydantic import BaseModel
from enum import Enum
from datetime import datetime


class CmdId(str, Enum):
    """"""

    EN_CMD_ID_INVALID = 'EN_CMD_ID_INVALID'
    """非法cmd"""
    EN_CMD_ID_SEND_MSG = 'EN_CMD_ID_SEND_MSG'
    """msg_svr
    发消息='发消息'
    """
    EN_CMD_ID_SYNC_MSG = 'EN_CMD_ID_SYNC_MSG'
    """sync_msg_svr
    同步消息='同步消息'
    """
    EN_CMD_ID_SYNC_RELATION = 'EN_CMD_ID_SYNC_RELATION'
    """同步相关链"""
    EN_CMD_ID_SYNC_ACK = 'EN_CMD_ID_SYNC_ACK'
    """客户端同步消息完成后，向服务器确认同步进度"""
    EN_CMD_ID_SYNC_FETCH_SESSION_MSGS = 'EN_CMD_ID_SYNC_FETCH_SESSION_MSGS'
    """多端同步版本拉取消息"""
    EN_CMD_ID_SESSION_SVR_GET_SESSIONS = 'EN_CMD_ID_SESSION_SVR_GET_SESSIONS'
    """session_svr
    拉会话列表='拉会话列表'
    """
    EN_CMD_ID_SESSION_SVR_NEW_SESSIONS = 'EN_CMD_ID_SESSION_SVR_NEW_SESSIONS'
    """新消息到达时获取会话列表"""
    EN_CMD_ID_SESSION_SVR_ACK_SESSIONS = 'EN_CMD_ID_SESSION_SVR_ACK_SESSIONS'
    """获取已读位置有更新的会话列表"""
    EN_CMD_ID_SESSION_SVR_UPDATE_ACK = 'EN_CMD_ID_SESSION_SVR_UPDATE_ACK'
    """更新已读进度"""
    EN_CMD_ID_SESSION_SVR_SET_TOP = 'EN_CMD_ID_SESSION_SVR_SET_TOP'
    """置顶/取消置顶"""
    EN_CMD_ID_SESSION_SVR_REMOVE_SESSION = (
        'EN_CMD_ID_SESSION_SVR_REMOVE_SESSION'
    )
    """删除会话"""
    EN_CMD_ID_SESSION_SVR_SINGLE_UNREAD = 'EN_CMD_ID_SESSION_SVR_SINGLE_UNREAD'
    """单聊未读信息数"""
    EN_CMD_ID_SESSION_SVR_MY_GROUP_UNREAD = (
        'EN_CMD_ID_SESSION_SVR_MY_GROUP_UNREAD'
    )
    """我创建的应援团未读数"""
    EN_CMD_ID_SESSION_SVR_UPDATE_UNFLW_READ = (
        'EN_CMD_ID_SESSION_SVR_UPDATE_UNFLW_READ'
    )
    """未关注的人批量设置为已读"""
    EN_CMD_ID_SESSION_SVR_GROUP_ASSIS_MSG = (
        'EN_CMD_ID_SESSION_SVR_GROUP_ASSIS_MSG'
    )
    """应援团消息助手"""
    EN_CMD_ID_SESSION_SVR_ACK_ASSIS_MSG = 'EN_CMD_ID_SESSION_SVR_ACK_ASSIS_MSG'
    """更新应援团小助手消息已拉取进度"""
    EN_CMD_ID_SESSION_SVR_SESSION_DETAIL = (
        'EN_CMD_ID_SESSION_SVR_SESSION_DETAIL'
    )
    """拉会话详情"""
    EN_CMD_ID_SESSION_SVR_BATCH_SESS_DETAIL = (
        'EN_CMD_ID_SESSION_SVR_BATCH_SESS_DETAIL'
    )
    """批量拉会话详情"""
    EN_CMD_ID_SESSION_SVR_BATCH_RM_SESSIONS = (
        'EN_CMD_ID_SESSION_SVR_BATCH_RM_SESSIONS'
    )
    """批量删除会话"""


class ENUM_BIZ_MSG_TYPE(str, Enum):
    """"""

    BIZ_MSG_TYPE_NORMAL = 'BIZ_MSG_TYPE_NORMAL'
    """"""
    BIZ_MSG_TYPE_CARD_VIDEO = 'BIZ_MSG_TYPE_CARD_VIDEO'
    """"""


class MsgSource(str, Enum):
    """消息来源"""

    EN_MSG_SOURCE_UNKONW = 'EN_MSG_SOURCE_UNKONW'
    """"""
    EN_MSG_SOURCE_IOS = 'EN_MSG_SOURCE_IOS'
    """"""
    EN_MSG_SOURCE_ANDRIOD = 'EN_MSG_SOURCE_ANDRIOD'
    """"""
    EN_MSG_SOURCE_H5 = 'EN_MSG_SOURCE_H5'
    """"""
    EN_MSG_SOURCE_PC = 'EN_MSG_SOURCE_PC'
    """"""
    EN_MSG_SOURCE_BACKSTAGE = 'EN_MSG_SOURCE_BACKSTAGE'
    """"""
    EN_MSG_SOURCE_BIZ = 'EN_MSG_SOURCE_BIZ'
    """"""
    EN_MSG_SOURCE_WEB = 'EN_MSG_SOURCE_WEB'
    """"""
    EN_MSG_SOURCE_AUTOREPLY_BY_FOLLOWED = 'EN_MSG_SOURCE_AUTOREPLY_BY_FOLLOWED'
    """"""
    EN_MSG_SOURCE_AUTOREPLY_BY_RECEIVE_MSG = (
        'EN_MSG_SOURCE_AUTOREPLY_BY_RECEIVE_MSG'
    )
    """"""
    EN_MSG_SOURCE_AUTOREPLY_BY_KEYWORDS = 'EN_MSG_SOURCE_AUTOREPLY_BY_KEYWORDS'
    """"""
    EN_MSG_SOURCE_AUTOREPLY_BY_VOYAGE = 'EN_MSG_SOURCE_AUTOREPLY_BY_VOYAGE'
    """"""
    EN_MSG_SOURCE_VC_ATTACH_MSG = 'EN_MSG_SOURCE_VC_ATTACH_MSG'
    """"""


class MsgType(str, Enum):
    """消息类型"""

    EN_INVALID_MSG_TYPE = 'EN_INVALID_MSG_TYPE'
    """基础消息类型
    空空的~='空空的~'
    """
    EN_MSG_TYPE_TEXT = 'EN_MSG_TYPE_TEXT'
    """文本消息"""
    EN_MSG_TYPE_PIC = 'EN_MSG_TYPE_PIC'
    """图片消息"""
    EN_MSG_TYPE_AUDIO = 'EN_MSG_TYPE_AUDIO'
    """语音消息"""
    EN_MSG_TYPE_SHARE = 'EN_MSG_TYPE_SHARE'
    """分享消息"""
    EN_MSG_TYPE_DRAW_BACK = 'EN_MSG_TYPE_DRAW_BACK'
    """撤回消息"""
    EN_MSG_TYPE_CUSTOM_FACE = 'EN_MSG_TYPE_CUSTOM_FACE'
    """自定义表情"""
    EN_MSG_TYPE_SHARE_V2 = 'EN_MSG_TYPE_SHARE_V2'
    """分享v2消息"""
    EN_MSG_TYPE_SYS_CANCEL = 'EN_MSG_TYPE_SYS_CANCEL'
    """系统撤销"""
    EN_MSG_TYPE_MINI_PROGRAM = 'EN_MSG_TYPE_MINI_PROGRAM'
    """小程序"""
    EN_MSG_TYPE_NOTIFY_MSG = 'EN_MSG_TYPE_NOTIFY_MSG'
    """扩展消息类型
    业务通知='业务通知'
    """
    EN_MSG_TYPE_VIDEO_CARD = 'EN_MSG_TYPE_VIDEO_CARD'
    """视频卡片"""
    EN_MSG_TYPE_ARTICLE_CARD = 'EN_MSG_TYPE_ARTICLE_CARD'
    """专栏卡片"""
    EN_MSG_TYPE_PICTURE_CARD = 'EN_MSG_TYPE_PICTURE_CARD'
    """图片卡"""
    EN_MSG_TYPE_COMMON_SHARE_CARD = 'EN_MSG_TYPE_COMMON_SHARE_CARD'
    """异形卡"""
    EN_MSG_TYPE_BIZ_MSG_TYPE = 'EN_MSG_TYPE_BIZ_MSG_TYPE'
    """"""
    EN_MSG_TYPE_MODIFY_MSG_TYPE = 'EN_MSG_TYPE_MODIFY_MSG_TYPE'
    """"""
    EN_MSG_TYPE_GROUP_MEMBER_CHANGED = 'EN_MSG_TYPE_GROUP_MEMBER_CHANGED'
    """功能类系统消息类型
    群成员变更='群成员变更'
    """
    EN_MSG_TYPE_GROUP_STATUS_CHANGED = 'EN_MSG_TYPE_GROUP_STATUS_CHANGED'
    """群状态变更"""
    EN_MSG_TYPE_GROUP_DYNAMIC_CHANGED = 'EN_MSG_TYPE_GROUP_DYNAMIC_CHANGED'
    """群动态变更"""
    EN_MSG_TYPE_GROUP_LIST_CHANGED = 'EN_MSG_TYPE_GROUP_LIST_CHANGED'
    """群列表变更"""
    EM_MSG_TYPE_FRIEND_LIST_CHANGED = 'EM_MSG_TYPE_FRIEND_LIST_CHANGED'
    """好友列表变更"""
    EN_MSG_TYPE_GROUP_DETAIL_CHANGED = 'EN_MSG_TYPE_GROUP_DETAIL_CHANGED'
    """群详情发生变化"""
    EN_MSG_TYPE_GROUP_MEMBER_ROLE_CHANGED = (
        'EN_MSG_TYPE_GROUP_MEMBER_ROLE_CHANGED'
    )
    """群成员角色发生变化"""
    EN_MSG_TYPE_NOTICE_WATCH_LIST = 'EN_MSG_TYPE_NOTICE_WATCH_LIST'
    """"""
    EN_MSG_TYPE_NOTIFY_NEW_REPLY_RECIEVED = (
        'EN_MSG_TYPE_NOTIFY_NEW_REPLY_RECIEVED'
    )
    """消息系统，收到新的reply"""
    EN_MSG_TYPE_NOTIFY_NEW_AT_RECIEVED = 'EN_MSG_TYPE_NOTIFY_NEW_AT_RECIEVED'
    """"""
    EN_MSG_TYPE_NOTIFY_NEW_PRAISE_RECIEVED = (
        'EN_MSG_TYPE_NOTIFY_NEW_PRAISE_RECIEVED'
    )
    """"""
    EN_MSG_TYPE_NOTIFY_NEW_UP_RECIEVED = 'EN_MSG_TYPE_NOTIFY_NEW_UP_RECIEVED'
    """"""
    EN_MSG_TYPE_NOTIFY_NEW_REPLY_RECIEVED_V2 = (
        'EN_MSG_TYPE_NOTIFY_NEW_REPLY_RECIEVED_V2'
    )
    """"""
    EN_MSG_TYPE_NOTIFY_NEW_AT_RECIEVED_V2 = (
        'EN_MSG_TYPE_NOTIFY_NEW_AT_RECIEVED_V2'
    )
    """"""
    EN_MSG_TYPE_NOTIFY_NEW_PRAISE_RECIEVED_V2 = (
        'EN_MSG_TYPE_NOTIFY_NEW_PRAISE_RECIEVED_V2'
    )
    """"""
    EN_MSG_TYPE_GROUP_DETAIL_CHANGED_MULTI = (
        'EN_MSG_TYPE_GROUP_DETAIL_CHANGED_MULTI'
    )
    """群详情发生变化,多端同步版本需要即时消息，无需落地"""
    EN_MSG_TYPE_GROUP_MEMBER_ROLE_CHANGED_MULTI = (
        'EN_MSG_TYPE_GROUP_MEMBER_ROLE_CHANGED_MULTI'
    )
    """群成员角色发生变化,多端同步版本需要即时消息，无需落地"""
    EN_MSG_TYPE_NOTIFY_ANTI_DISTURB = 'EN_MSG_TYPE_NOTIFY_ANTI_DISTURB'
    """"""
    EN_MSG_TYPE_SYS_GROUP_DISSOLVED = 'EN_MSG_TYPE_SYS_GROUP_DISSOLVED'
    """系统通知栏消息类型
    群解散='群解散'
    """
    EN_MSG_TYPE_SYS_GROUP_JOINED = 'EN_MSG_TYPE_SYS_GROUP_JOINED'
    """入群"""
    EN_MSG_TYPE_SYS_GROUP_MEMBER_EXITED = 'EN_MSG_TYPE_SYS_GROUP_MEMBER_EXITED'
    """成员主动退群"""
    EN_MSG_TYPE_SYS_GROUP_ADMIN_FIRED = 'EN_MSG_TYPE_SYS_GROUP_ADMIN_FIRED'
    """房管被撤"""
    EN_MSG_TYPE_SYS_GROUP_MEMBER_KICKED = 'EN_MSG_TYPE_SYS_GROUP_MEMBER_KICKED'
    """成员被T"""
    EN_MSG_TYPE_SYS_GROUP_ADMIN_KICK_OFF = (
        'EN_MSG_TYPE_SYS_GROUP_ADMIN_KICK_OFF'
    )
    """管理T人"""
    EN_MSG_TYPE_SYS_GROUP_ADMIN_DUTY = 'EN_MSG_TYPE_SYS_GROUP_ADMIN_DUTY'
    """管理上任"""
    EN_MSG_TYPE_SYS_GROUP_AUTO_CREATED = 'EN_MSG_TYPE_SYS_GROUP_AUTO_CREATED'
    """自动创建"""
    EN_MSG_TYPE_SYS_FRIEND_APPLY = 'EN_MSG_TYPE_SYS_FRIEND_APPLY'
    """好友申请"""
    EN_MSG_TYPE_SYS_FRIEND_APPLY_ACK = 'EN_MSG_TYPE_SYS_FRIEND_APPLY_ACK'
    """好友申请通过"""
    EN_MSG_TYPE_SYS_GROUP_APPLY_FOR_JOINING = (
        'EN_MSG_TYPE_SYS_GROUP_APPLY_FOR_JOINING'
    )
    """用户加群申请"""
    EN_MSG_TYPE_SYS_GROUP_ADMIN_ACCEPTED_USER_APPLY = (
        'EN_MSG_TYPE_SYS_GROUP_ADMIN_ACCEPTED_USER_APPLY'
    )
    """通知管理员,有其他管理员已经同意用户加群"""
    EN_MSG_TYPE_CHAT_MEMBER_JOINED = 'EN_MSG_TYPE_CHAT_MEMBER_JOINED'
    """聊天窗口通知消息类型
    入群='入群'
    """
    EN_MSG_TYPE_CHAT_MEMBER_EXITED = 'EN_MSG_TYPE_CHAT_MEMBER_EXITED'
    """退群"""
    EN_MSG_TYPE_CHAT_GROUP_FREEZED = 'EN_MSG_TYPE_CHAT_GROUP_FREEZED'
    """冻结"""
    EN_MSG_TYPE_CHAT_GROUP_DISSOLVED = 'EN_MSG_TYPE_CHAT_GROUP_DISSOLVED'
    """解散"""
    EN_MSG_TYPE_CHAT_GROUP_CREATED = 'EN_MSG_TYPE_CHAT_GROUP_CREATED'
    """开通应援团"""
    EN_MSG_TYPE_CHAT_POPUP_SESSION = 'EN_MSG_TYPE_CHAT_POPUP_SESSION'
    """弹出会话"""


class RecverType(str, Enum):
    """接收方类型"""

    EN_NO_MEANING = 'EN_NO_MEANING'
    """"""
    EN_RECVER_TYPE_PEER = 'EN_RECVER_TYPE_PEER'
    """单人"""
    EN_RECVER_TYPE_GROUP = 'EN_RECVER_TYPE_GROUP'
    """群"""
    EN_RECVER_TYPE_PEERS = 'EN_RECVER_TYPE_PEERS'
    """多人"""


class RelationLogType(str, Enum):
    """"""

    EN_INVALID_LOG_TYPE = 'EN_INVALID_LOG_TYPE'
    """"""
    EN_ADD_FRIEND = 'EN_ADD_FRIEND'
    """添加好友"""
    EN_REMOVE_FRIEND = 'EN_REMOVE_FRIEND'
    """删除好友"""
    EN_JOIN_GROUP = 'EN_JOIN_GROUP'
    """加入群"""
    EN_EXIT_GROUP = 'EN_EXIT_GROUP'
    """退出群"""


class SESSION_TYPE(str, Enum):
    """"""

    INVALID_SESSION_TYPE = 'INVALID_SESSION_TYPE'
    """"""
    UN_FOLD_SESSION = 'UN_FOLD_SESSION'
    """"""
    UN_FOLLOW_SINGLE_SESSION = 'UN_FOLLOW_SINGLE_SESSION'
    """"""
    MY_GROUP_SESSION = 'MY_GROUP_SESSION'
    """"""
    ALL_SESSION = 'ALL_SESSION'
    """"""


class AccountInfo(BaseModel):
    """"""

    name: builtins.str
    """"""
    pic_url: builtins.str
    """"""


class FriendRelation(BaseModel):
    """"""

    uid: builtins.int
    """用户mid"""
    user_name: builtins.str
    """用户昵称"""
    face: builtins.str
    """头像url"""
    vip_level: builtins.int
    """vip类型
    0:无 1:月度大会员 2:年度大会员
    """


class GroupRelation(BaseModel):
    """"""

    group_id: builtins.int
    """"""
    owner_uid: builtins.int
    """"""
    group_type: builtins.int
    """"""
    group_level: builtins.int
    """"""
    group_cover: builtins.str
    """"""
    group_name: builtins.str
    """"""
    group_notice: builtins.str
    """"""
    status: builtins.int
    """"""
    member_role: builtins.int
    """"""
    fans_medal_name: builtins.str
    """"""
    room_id: builtins.int
    """"""


class HighText(BaseModel):
    """关键词高亮文本"""

    title: builtins.str
    """"""
    url: builtins.str
    """"""
    index: builtins.int
    """表示高亮文本应该高亮第几个匹配的文本，ps：比如，“有疑问请联系客服，联系客服时，请说明具体的情况”，一共有2个匹配的文本，要高亮第一个匹配的，则index=1"""


class ImgInfo(BaseModel):
    """"""

    url: builtins.str
    """"""
    width: builtins.int
    """"""
    height: builtins.int
    """"""
    imageType: builtins.str
    """"""


class KeyHitInfos(BaseModel):
    """关键词命中信息"""

    toast: builtins.str
    """"""
    rule_id: builtins.int
    """"""
    high_text: "List[HighText]"
    """

        """


class Medal(BaseModel):
    """"""

    uid: builtins.int
    """"""
    medal_id: builtins.int
    """"""
    level: builtins.int
    """"""
    medal_name: builtins.str
    """"""
    score: builtins.int
    """"""
    intimacy: builtins.int
    """"""
    master_status: builtins.int
    """"""
    is_receive: builtins.int
    """"""
    medal_color_start: builtins.int
    """"""
    medal_color_end: builtins.int
    """"""
    medal_color_border: builtins.int
    """"""
    medal_color_name: builtins.int
    """"""
    medal_color_level: builtins.int
    """"""
    guard_level: builtins.int
    """"""


class Msg(BaseModel):
    """"""

    sender_uid: builtins.int
    """发送方mid"""
    receiver_type: RecverType
    """接收方类型"""
    receiver_id: builtins.int
    """接收方mid"""
    cli_msg_id: builtins.int
    """客户端的序列id,用于服务端去重"""
    msg_type: MsgType
    """消息类型"""
    content: builtins.str
    """消息内容"""
    msg_seqno: builtins.int
    """服务端的序列号x"""
    timestamp: builtins.int
    """消息发送时间（服务端时间）"""
    at_uids: List[builtins.int]
    """@用户列表"""
    recver_ids: List[builtins.int]
    """多人消息"""
    msg_key: builtins.int
    """消息唯一标示"""
    msg_status: builtins.int
    """消息状态"""
    sys_cancel: builtins.bool
    """是否为系统撤销"""
    notify_code: builtins.str
    """通知码"""
    msg_source: MsgSource
    """消息来源"""
    new_face_version: builtins.int
    """如果msg.content有表情字符，则该参数需要置为1"""
    key_hit_infos: Optional["KeyHitInfos"] = None
    """命中关键词信息"""


class RelationLog(BaseModel):
    """"""

    log_type: RelationLogType
    """操作类型"""
    oplog_seqno: builtins.int
    """操作seqno"""
    friend_relation: Optional["FriendRelation"] = None
    """好友信息"""
    group_relation: Optional["GroupRelation"] = None
    """群信息"""


class SessionInfo(BaseModel):
    """会话详情"""

    talker_id: builtins.int
    """"""
    session_type: builtins.int
    """"""
    at_seqno: builtins.int
    """"""
    top_ts: builtins.int
    """"""
    group_name: builtins.str
    """"""
    group_cover: builtins.str
    """"""
    is_follow: builtins.int
    """"""
    is_dnd: builtins.int
    """"""
    ack_seqno: builtins.int
    """"""
    ack_ts: builtins.int
    """"""
    session_ts: builtins.int
    """"""
    unread_count: builtins.int
    """"""
    last_msg: Optional["Msg"] = None
    """"""
    group_type: builtins.int
    """"""
    can_fold: builtins.int
    """"""
    status: builtins.int
    """"""
    max_seqno: builtins.int
    """"""
    new_push_msg: builtins.int
    """会话是否有业务通知"""
    setting: builtins.int
    """接收方是否设置接受推送"""
    is_guardian: builtins.int
    """"""
    is_intercept: builtins.int
    """"""
    is_trust: builtins.int
    """"""
    system_msg_type: builtins.int
    """"""
    account_info: Optional["AccountInfo"] = None
    """"""
    live_status: builtins.int
    """"""
    biz_msg_unread_count: builtins.int
    """"""
    user_label: Optional["UserLabel"] = None
    """"""


class UserLabel(BaseModel):
    """"""

    label_type: builtins.int
    """"""
    medal: Optional["Medal"] = None
    """"""
    guardian_relation: builtins.int
    """"""


AccountInfo.update_forward_refs()
ImgInfo.update_forward_refs()
FriendRelation.update_forward_refs()
KeyHitInfos.update_forward_refs()
Msg.update_forward_refs()
RelationLog.update_forward_refs()
Medal.update_forward_refs()
GroupRelation.update_forward_refs()
SessionInfo.update_forward_refs()
HighText.update_forward_refs()
UserLabel.update_forward_refs()
