"""
Generated by generator/gen_pydantic.py. DO NOT EDIT!
isort:skip_file
"""
import builtins
from typing import List, Dict, Any, Optional
from pydantic import BaseModel
from enum import Enum
from datetime import datetime


class Sync(BaseModel):
    """"""

    note_id: builtins.int
    """笔记id"""
    hash: builtins.str
    """唯一标示"""


Sync.update_forward_refs()
