"""
Generated by generator/gen_pydantic.py. DO NOT EDIT!
isort:skip_file
"""

import builtins
from typing import List, Dict, Any, Optional
from pydantic import BaseModel
from enum import Enum
from datetime import datetime


class LinkType(str, Enum):
    """"""

    LINK_TYPE_UNKNOWN = 'LINK_TYPE_UNKNOWN'
    """未知"""
    LINK_TYPE_BANGUMI = 'LINK_TYPE_BANGUMI'
    """番剧"""
    LINK_TYPE_VIDEO = 'LINK_TYPE_VIDEO'
    """视频"""
    LINK_TYPE_LIVE = 'LINK_TYPE_LIVE'
    """直播"""


class PageBlackList(BaseModel):
    """"""

    id: builtins.str
    """"""


class PageView(BaseModel):
    """"""

    id: builtins.str
    """"""


class PushMessageResp(BaseModel):
    """"""

    class PushMessageResp_Biz(str, Enum):
        BIZ_UNKNOWN = 'BIZ_UNKNOWN'
        """未知"""
        BIZ_VIDEO = 'BIZ_VIDEO'
        """视频"""
        BIZ_LIVE = 'BIZ_LIVE'
        """直播"""
        BIZ_ACTIVITY = 'BIZ_ACTIVITY'
        """活动"""

    """未知"""
    """视频"""
    """直播"""
    """活动"""

    class PushMessageResp_Type(str, Enum):
        TYPE_UNKNOWN = 'TYPE_UNKNOWN'
        """未知"""
        TYPE_DEFAULT = 'TYPE_DEFAULT'
        """默认"""
        TYPE_HOT = 'TYPE_HOT'
        """热门"""
        TYPE_REALTIME = 'TYPE_REALTIME'
        """实时"""
        TYPE_RECOMMEND = 'TYPE_RECOMMEND'
        """推荐"""

    """未知"""
    """默认"""
    """热门"""
    """实时"""
    """推荐"""

    class PushMessageResp_Position(str, Enum):
        POS_UNKNOWN = 'POS_UNKNOWN'
        """未知"""
        POS_TOP = 'POS_TOP'
        """顶部"""

    """未知"""
    """顶部"""
    old_taskid: builtins.int
    """Deprecated: 推送任务id，使用string"""
    biz: PushMessageResp_Biz
    """业务
    1:是视频 2:是直播 3:是活动
    """
    type: PushMessageResp_Type
    """类型
    1:是默认 2:是热门 3:是实时 4:是推荐
    """
    title: builtins.str
    """主标题"""
    summary: builtins.str
    """副标题"""
    img: builtins.str
    """图片地址"""
    link: builtins.str
    """跳转地址"""
    position: PushMessageResp_Position
    """展示位置，1是顶部"""
    duration: builtins.int
    """展示时长（单位：秒），默认3秒"""
    expire: builtins.int
    """失效时间"""
    taskid: builtins.str
    """推送任务id"""
    page_blackList: "List[PageBlackList]"
    """应用内推送黑名单
        UGC:     ugc-video-detail
        PGC:     pgc-video-detail
        一起看:   pgc-video-detail-theater
        直播:     live-room-detail
        Story:    ugc-video-detail-vertical
        播单黑名单 playlist-video-detail
        """
    page_view: "List[PageView]"
    """预留pvid"""
    target_resource: Optional["TargetResource"] = None
    """跳转资源"""
    image_frame: builtins.int
    """"""
    image_marker: builtins.int
    """"""
    image_position: builtins.int
    """"""
    job: builtins.int
    """"""


class TargetResource(BaseModel):
    """"""

    Type: LinkType
    """直播:   roomid
    UGC:   avid
    PGC:   seasonid
    Story: avid
    举个例子
    Type: LINK_TYPE_BANGUMI (番剧)
    Resource: {"seasonid":"123"}

    Type: LINK_TYPE_VIDEO (视频)
    Resource: {"avid":"123"}

    Type: LINK_TYPE_LIVE (直播)
    Resource: {"roomid":"123"}
    """
    Resource: Dict[builtins.str, builtins.str]
    """"""


PageView.update_forward_refs()
PushMessageResp.update_forward_refs()
PageBlackList.update_forward_refs()
TargetResource.update_forward_refs()
